### ISSUE TITLE
Provide Exponential backoff for retries in a JetStream Consumer

### ISSUE THREAD

**Issue by ColinSullivan1** [nats-io/nats-server#2748] opened 2021-12-15 18:58 UTC
## Feature Request
Provide an exponential backoff (or equivalent) for retries with a JetStream Consumer.

#### Use Case:
At scale this will ease pressure on the system and applications that wait to acknowledge for various reasons (out of order messages, grouping messages in a transaction, etc) would behave better.

#### Proposed Change:
Add a consumer creation options that allows for exponential retry backoff over a period of time.

#### Who Benefits From The Change(s)?
Any user of NATS JetStream.

#### Alternative Approaches
Applications would specify a large number of max-redeliveries combined with ack wait and application side logic.

**Comment by andreib1** [comment] 2021-12-16 05:53
If this is for push, it is a duplicate of https://github.com/nats-io/nats-server/issues/2042

**Comment by derekcollison** [comment] 2023-01-06 17:17
Nak with delay was implemented.

**Closed by derekcollison** 2023-01-06 17:17 UTC
Labels: 🎉 enhancement
