### ISSUE TITLE
Okay when using wildcard based certs and TLS but experience repeated disconnects using hostname based certs

### ISSUE THREAD

**Issue by rpc180** [nats-io/nats-server#756] opened 2018-09-24 18:20 UTC
- [x ] Defect
 - [ ] Feature Request or Change Proposal
 
## Defects 
Using gnatsd excuted on a Windows Server 2016 VM joined to a Microsoft Active Directory domain.  The domain has Microsoft Intermediate Certificate Authority capable of issuing certificates with Server and Client Authentication templates.

When using a .pem converted cert authority issued server authentication certificate with (for example) subject name as CN=dev-nats.domainname.com our connecting javascript client appears to negotiate a TLS handshake and then immediately registers a disconnect error.  The NATS output also shows the same disconnect.  Our javascript client re-attempts connection, establishes the TLS handshake and then experiences the disconnect error again.  This pattern repeats until the client or NATS instance is force-closed.

However, if the server authentication certificate is issued with subject name as CN=*.domainname.com (a wildcard certificate) our javascript client will connect and remain connected.

 - [x ] Included `gnatsd -DV` output
[628] 2018/09/24 14:02:04.933776 [[32mINF[0m] Starting nats-server version 1.3.0
[628] 2018/09/24 14:02:04.933776 [[36mDBG[0m] Go build version go1.11
[628] 2018/09/24 14:02:04.934775 [[32mINF[0m] Git commit [not set]
[628] 2018/09/24 14:02:04.935775 [[32mINF[0m] Listening for client connections on 0.0.0.0:4443
[628] 2018/09/24 14:02:04.935775 [[32mINF[0m] TLS required for client connections
[628] 2018/09/24 14:02:04.935775 [[36mDBG[0m] Server id is zcTtQ92rHbaFqvnL59gLq6
[628] 2018/09/24 14:02:04.935775 [[32mINF[0m] Server is ready
[628] 2018/09/24 14:02:10.053061 [[36mDBG[0m] 10.136.36.21:65278 - cid:1 - Client connection created
[628] 2018/09/24 14:02:10.053061 [[36mDBG[0m] 10.136.36.21:65278 - cid:1 - Starting TLS client connection handshake
[628] 2018/09/24 14:02:10.068825 [[36mDBG[0m] 10.136.36.21:65278 - cid:1 - TLS handshake complete
[628] 2018/09/24 14:02:10.068825 [[36mDBG[0m] 10.136.36.21:65278 - cid:1 - TLS version 1.2, cipher suite TLS_RSA_WITH_AES_256_CBC_SHA
[628] 2018/09/24 14:02:10.069863 [[36mDBG[0m] 10.136.36.21:65278 - cid:1 - Client connection closed
[628] 2018/09/24 14:02:11.364917 [[36mDBG[0m] 10.136.36.21:65281 - cid:2 - Client connection created
[628] 2018/09/24 14:02:11.364917 [[36mDBG[0m] 10.136.36.21:65281 - cid:2 - Starting TLS client connection handshake
[628] 2018/09/24 14:02:11.381583 [[36mDBG[0m] 10.136.36.21:65281 - cid:2 - TLS handshake complete
[628] 2018/09/24 14:02:11.381583 [[36mDBG[0m] 10.136.36.21:65281 - cid:2 - TLS version 1.2, cipher suite TLS_RSA_WITH_AES_256_CBC_SHA
[628] 2018/09/24 14:02:11.382612 [[36mDBG[0m] 10.136.36.21:65281 - cid:2 - Client connection closed
[628] 2018/09/24 14:02:11.387606 [[36mDBG[0m] 10.136.36.21:65282 - cid:3 - Client connection created
[628] 2018/09/24 14:02:11.387606 [[36mDBG[0m] 10.136.36.21:65282 - cid:3 - Starting TLS client connection handshake
[628] 2018/09/24 14:02:11.394598 [[36mDBG[0m] 10.136.36.21:65283 - cid:4 - Client connection created
[628] 2018/09/24 14:02:11.394598 [[36mDBG[0m] 10.136.36.21:65283 - cid:4 - Starting TLS client connection handshake
[628] 2018/09/24 14:02:11.403556 [[36mDBG[0m] 10.136.36.21:65282 - cid:3 - TLS handshake complete
[628] 2018/09/24 14:02:11.403556 [[36mDBG[0m] 10.136.36.21:65282 - cid:3 - TLS version 1.2, cipher suite TLS_RSA_WITH_AES_256_CBC_SHA
[628] 2018/09/24 14:02:11.404581 [[36mDBG[0m] 10.136.36.21:65282 - cid:3 - Client connection closed
pattern repeats until client or NATS is force closed.

 - [ ] Included a [Minimal, Complete, and Verifiable example] (http://stackoverflow.com/help/mcve)
 
#### Expected result:
Both CN=hostname.domainname.com and CN=*.domainname.com subject name server authentication certificates should result in successful and stable connections to NATS endpoint.
 
#### Actual result:
Wildcard subject name server authentication certificate remains stable.  CN=hostname.domainname.com results in repeated TLS handshake completed/immediate disconnect cycles.
 
#### Use Case:
Tying to leverage Microsoft certificate services to deploy certifcates to VMs running nats based on the VM's Windows hostname.  We are trying to avoid using a wildcard, localhost, or other kind of "generalized" subject name for the certificate.

**Comment by rpc180** [comment] 2018-09-24 18:49
BTW - we are certainly open to the possibility that something in our javascript client may be causing the connection reset.  We're not sure if the NATS server presents a name that might "mis-match" with the certificate we are using.  When certs are used for TLS, is there a value we should be using for the cert's subject name (like the "serverID" from the initialization output above)?

**Comment by aricart** [comment] 2018-09-26 20:39
@rpc180 What version of node-nats are you using?

**Comment by ColinSullivan1** [comment] 2018-09-26 21:07
@rpc180 , regarding usage of the "serverID" - great question, but you don't need to configure anything specific for NATS in the certificates beyond the hostname(s) or equivalent wildcard.  This sounds like a lower level TLS issue, so debugging node as @aricart suggested is a good first step.  Another alternative to narrow this down is to use another NATS client (preferably golang) to see if the issue is with server or client.

**Comment by rpc180** [comment] 2018-09-27 16:06
Dev team responded with the following:
nodejs version: 8.11.4
node-nats version: 0.8.10
For the node_debug=tls key pair, that should be placed in the client or is that to be included in the nats.config file?

**Comment by aricart** [comment] 2018-09-27 16:36
@rpc180 I think the issue you are running into is this:
https://github.com/nats-io/node-nats/pull/231

The current gnatsd is omitting some values that could be affecting the TLS handshake.
Please upgrade your node-nats client to the current (npm is hosting v1.0.1).

The `node_debug=tls` is set on the environment. Please try updating the node-nats client before further debugging.

**Comment by rpc180** [comment] 2018-09-27 16:40
Thanks, I'll relay to our developers and see if we can roll this into our next revision to check.

**Comment by aricart** [comment] 2018-10-01 14:05
@rpc180 did updating to the current node-nats solve the issue? If so let me know so I can close this issue.

**Comment by rpc180** [comment] 2018-10-01 15:14
Hi our lead developer who is looking into this hasn't been able to yet.  Word is we're going to put it into our next sprint which starts later this week.

**Comment by derekcollison** [comment] 2019-05-10 01:24
I am closing this for now, feel free to re-open if needed.

**Closed by derekcollison** 2019-05-10 01:24 UTC
