### ISSUE TITLE
【memory leak】cluster mode memory leak

### ISSUE THREAD

**Issue by zxq911** [nats-io/nats-server#1794] opened 2021-01-06 03:42 UTC
We run nats-server cluster with many nodes in production。
Client use connection pools to connect server，then run 3 days

-  1day： memory increase to 1.5GB
-  2day： memory increase to 2.5GB
-  3day：memory increase to 3.1GB - 4GB
-  end：the sever crash，only restart to reset memory

We upgrade to nats-server 2.1.8，but no fix this question。
Can you fix this bug？

**Comment by derekcollison** [comment] 2021-01-06 03:45
Check the monitoring ports under varz for lots of connections and/or leaked subscriptions.

**Comment by zxq911** [comment] 2021-01-06 06:01
> Check the monitoring ports under varz for lots of connections and/or leaked subscriptions.

How to check leaked， check connections counts， or subscriptions counts？
one server connect has 1.8k connections and 8.7million subscriptions。
why the subscriptions can not release
I doubt too many subscriptions cause this question， but how to fix。

**Comment by derekcollison** [comment] 2021-01-06 13:55
https://docs.nats.io/nats-streaming-concepts/monitoring

Do the subscriptions continue to increase over time? If so you have applications that are not unsubscribing.

**Comment by kozlovic** [comment] 2021-01-06 15:36
@zxq911 To add to Derek's comments: first, correction to the link (the one he posted was form NATS Streaming): https://docs.nats.io/nats-server/configuration/monitoring

The idea is to check if you have a number of NATS objects that keep accumulating, it can be connections or subscriptions. If you observe that the count grows overtime, it CAN explain the memory usage increase. We will have to figure out if those subscriptions are a result of your applications creating too many without closing unneeded ones, or if the "leak" is a result of a bug in the server.

For instance, to get some details about what the subscriptions are about, you can check the following endpoint:
```
http://<host>:<monitoring port>/subsz?subs=1&limit=10000
```
The `limit=10000` causes the server to return 10,000 subscriptions, the default is 1024. You can use any number you feel comfortable with. Having a look at the subscription subject may help you/us identify what are those subscriptions and if it makes sense that there are that many.

**Comment by alexrudd** [comment] 2021-03-16 15:25
Hey,

Might be having a similar problem but doesn't seem to be caused by holding onto resources. The nats server in our test environment has been running since 2021-02-01 and slowly using more and more memory in that time.

First pic is of the resource usage (% CPU/Mem):

![resource usage](https://user-images.githubusercontent.com/3588652/111333930-09dc7e80-866b-11eb-93f0-63e170c6a318.png)

Second pic is of the number of connections, subscriptions, and bytes in (from the varz endpoint) in that time:

![connections and subscriptions](https://user-images.githubusercontent.com/3588652/111333783-e44f7500-866a-11eb-8b8a-dbf56fa76c81.png)

The ECS orchestrator killed our NATS container today for using too much memory:

![image](https://user-images.githubusercontent.com/3588652/111334662-aa32a300-866b-11eb-954d-b212adb8fb12.png)

**Comment by ripienaar** [comment] 2021-03-16 15:55
It's hard to say on versions built with go prior to 1.16 what's going on since when it releases memory it uses MADV_FREE - which tells the kernel not to reclaim the memory unless the kernel needs it.  The side effect of this was that container orchestrators would kill off go programs for using too much memory when in fact they are using a lot less.

In Go 1.16 they moved to MADV_DONTNEED which will immediately cause the memory to be reclaimed. Our 2.2.0 release is built using go 1.16, you might well seen an impovement by looking at that.

**Comment by alexrudd** [comment] 2021-03-16 16:15
Oh cool, that's useful to know. I forgot to include the version but we're on `2.1.9`. Will try upgrading and see what happens

**Comment by ripienaar** [comment] 2021-03-16 16:17
Cool - not saying its impossible we have a leak, but I know a lot of missreporting is going on due to above.  Go team finally recognised the impact is too big and tweaked things.  Hope it helps!

**Comment by mvisonneau** [comment] 2021-07-20 11:21
:wave: I have been able to observe similar patterns on `v2.3.1`:

![image](https://user-images.githubusercontent.com/1761583/126315589-e8cea2f0-eb95-4918-a898-e57579877f62.png)
![image](https://user-images.githubusercontent.com/1761583/126315650-c4223f30-aef6-4d19-80f8-2fa3005757b5.png)
![image](https://user-images.githubusercontent.com/1761583/126315688-faef663d-effb-4a4f-b658-13dfe3a6ebe3.png)

**Comment by derekcollison** [comment] 2021-07-20 14:07
Please upgrade to 2.3.2 version which does have a fix for this IIRC.

**Comment by mvisonneau** [comment] 2021-07-20 14:32
Thanks for the info @derekcollison, will do :+1:

**Comment by derekcollison** [comment] 2021-07-20 15:04
Keep us posted, and thanks!

**Comment by mvisonneau** [comment] 2021-07-21 13:21
I believe the issue was on my end, at first sight, I was still experiencing a similar behaviour after upgrading to `2.3.2`:

![image](https://user-images.githubusercontent.com/1761583/126494620-0b137c7e-bc3d-4ef3-8ae2-309fe67a1334.png)

It turns out that I had some network misconfiguration which was dropping, not all, but some of the cluster traffic on `TCP/6222`

```
Jul 21 10:10:47.829: nats/nats-1:51920 -> nats-0.nats.nats.svc.cluster.local:6222 Policy denied DROPPED (TCP Flags: SYN)
Jul 21 10:10:47.829: nats/nats-1:51920 -> nats-0.nats.nats.svc.cluster.local:6222 Policy denied DROPPED (TCP Flags: SYN)
Jul 21 10:10:47.830: nats/nats-2:35662 -> nats-0.nats.nats.svc.cluster.local:6222 Policy denied DROPPED (TCP Flags: SYN)
Jul 21 10:10:47.830: nats/nats-2:35662 -> nats-0.nats.nats.svc.cluster.local:6222 Policy denied DROPPED (TCP Flags: SYN)
Jul 21 10:10:48.447: nats-0.nats.nats.svc.cluster.local:43136 -> nats/nats-1:6222 Policy denied DROPPED (TCP Flags: SYN)
Jul 21 10:10:48.447: nats-0.nats.nats.svc.cluster.local:43136 -> nats/nats-1:6222 Policy denied DROPPED (TCP Flags: SYN)
Jul 21 10:10:48.467: nats-0.nats.nats.svc.cluster.local:44246 -> nats/nats-2:6222 Policy denied DROPPED (TCP Flags: SYN)
Jul 21 10:10:48.467: nats-0.nats.nats.svc.cluster.local:44246 -> nats/nats-2:6222 Policy denied DROPPED (TCP Flags: SYN)
```

After sorting out my network policy issue, the "leak" situation seems to be gone:

![image](https://user-images.githubusercontent.com/1761583/126495315-74848aae-070e-4610-8207-63583d558dc2.png)

Thanks a lot for your help on this! :bow:

**Closed** 2021-07-21 14:24 UTC
