### ISSUE TITLE
subscription count in subsz is wrong

### ISSUE THREAD

**Issue by ripienaar** [nats-io/nats-server#1065] opened 2019-07-10 10:31 UTC
SInce updating one of my brokers to 2.0.0 I noticed a slow increate in subscription counts - I also did a bunch of other updates like move to the newly renamed libraries etc so in order to find the cause I eventually concluded the server is just counting things wrongly.

![graph](https://i.imgur.com/9pY7ORr.png)

Ignoring the annoying popup, you can see a steady increase in subscriptions.

Data below is from the below dependency embedded in another go process:

```
github.com/nats-io/nats-server/v2 v2.0.1-0.20190701212751-a171864ae7df
```

```
$ curl -s http://localhost:6165/varz|jq .subscriptions
29256
```

I then tried to verify this number, and assuming I have no bugs in the script below I think the varz counter is off by a lot, comparing snapshots of connz over time I see no growth reflected there not in connection counts nor subscriptions:

```
$ curl "http://localhost:6165/connz?limit=200000&subs=1"|./countsubs.rb
Connections: 3659
Subscriptions: 25477
```

I also captured connz output over time 15:17, 15:56 and 10:07 the next day:

```
$ cat connz-1562685506.json|./countsubs.rb
Connections: 3657
Subscriptions: 25463
$ cat connz-1562687791.json|./countsubs.rb
Connections: 3658
Subscriptions: 25463
$ cat connz-1562687791.json|./countsubs.rb
Connections: 3658
Subscriptions: 25463
```

Using the script here:

```ruby
require "json"

subs = JSON.parse(STDIN.read)
puts "Connections: %d" % subs["connections"].length

count = 0

subs["connections"].each do |conn|
  count += subs.length if subs = conn["subscriptions_list"]
end

puts "Subscriptions: %d" % count
```

**Comment by derekcollison** [comment] 2019-07-10 11:16
If a utility application comes up and sends a request it will create a subscription every time and will then exit meaning it will not be part of 'connz' by default. You can see closed connections up to a certain amount (we use a ring buffer of 10,000 by default IIRC) using `state=closed` or `state=all`, e.g. `http://demo.nats.io:8222/connz?subs=1&state=closed`

**Comment by derekcollison** [comment] 2019-07-10 11:18
I apologize, I see that you are using `varz` which should be active connections.

**Comment by derekcollison** [comment] 2019-07-10 11:21
Setup for server you are monitoring, does it have routes, leafnodes, gateways etc?

**Comment by ripienaar** [comment] 2019-07-10 11:34
Only a 2 node cluster, nothing else fancy, no accounts even.  Basically no actual 2.0 features yet - was testing clustering stability only

**Comment by derekcollison** [comment] 2019-07-10 11:45
ok thanks will look into it.

**Comment by derekcollison** [comment] 2019-07-10 11:48
Applications doing Requests() or regular Subscriptions?

**Comment by ripienaar** [comment] 2019-07-10 11:50
Something is definitely not releasing here, another graph:

![mem v subs](https://i.imgur.com/ziwRasO.png)

This on the left axis is go_memstats_alloc_bytes that the usual prometheus exporter gather while the other axis is subscriptions as reported by varz

memory going up suggests that indeed somehow a subscription is staying somewhere but in a way that subsz does not report/expose.

The bulk are regular static subscriptions and then a reasonable amount of short lives connections doing something similar to Request() and then disconnecting.

**Comment by derekcollison** [comment] 2019-07-10 11:53
Could you describe "similar" to Request()? Do you create your own `_INBOX` or use the client language?
If you kill all of the applications does what does the varz subscriptions report?

**Comment by ripienaar** [comment] 2019-07-10 11:53
An unclustered one does not appear to exhibit the same behaviour, regarding the memory though above I cannot 100% say the memory increase is NATS related since as I said it is an embedded instance and I have some other stuff going on. But being so closely related its worth considering.

**Comment by derekcollison** [comment] 2019-07-10 11:54
Trying to setup a test to reproduce as we speak.

**Comment by ripienaar** [comment] 2019-07-10 11:56
I create a inbox, publish a request to 7k machines who will reply to that inbox and once done I close. Mixture of go and ruby (all on the older nats-go library, I ONLY updated the broker here)

In general it does what you expect varz connections and subscriptions grows and shrinks on normal client connections but then sometimes, it goes up.  The graph isnt like a straight line it stis flat then up then flat etc.

**Comment by ripienaar** [comment] 2019-07-10 12:18
I can do on demand dumps of all the active go routines, will do this every few hours and see if i can spot something useful - they dont seem to climb in tandem with this graph exactly but there is some increase.

**Comment by derekcollison** [comment] 2019-07-10 12:19
The subscriptions from the remote server will also show up but will be binary. What I mean is that if I create 1000 subs on "foo"  on both servers, the varz subscription count will be 1001 for both servers since 1 subscription is the remote interest in "foo".

If you kill all the apps does it go to zero?

**Comment by derekcollison** [comment] 2019-07-10 12:21
What version of go client?

**Comment by ripienaar** [comment] 2019-07-10 12:24
hmm, not sure i am following - but subs count on the 2 machines is not the same.  29263 vs 29422.  Connections are 3662 + 3657 between those.  Both showing the growth trend.

I cannot shut them down :) 

```
Summary of Middleware Client Flavour:

   go-nats go1.10.2 = 7290
   nats.go go1.12.6 = 5
     go-nats go1.10 = 3
```

Here I was using a ruby client `nats-pure (0.5.0)`

**Comment by ripienaar** [comment] 2019-07-10 12:26
the 7290 are the running servers I manage via this - they did not change to anything new. 
the 5 are some micro services that goes along with my broker
the 3, hmm, some machines failed a earlier upgrade so just slightly older of same as the 7290

**Comment by derekcollison** [comment] 2019-07-10 12:26
Yes that would make sense. When a server has interest its sends binary interest over the route, so in real world scenario that would make sense.

**Comment by ripienaar** [comment] 2019-07-10 12:27
ah damn, now I notice those are in fact go versions not client library versions....

**Comment by ripienaar** [comment] 2019-07-10 12:29
the 7290 would be go-nats fb0396ee0bdb8018b0fef30d6d1de798ce99cd05

**Comment by derekcollison** [comment] 2019-07-10 12:32
What is the date on that?

**Comment by ripienaar** [comment] 2019-07-10 12:35
rel 1.7.2 https://github.com/nats-io/go-nats/commit/fb0396ee0bdb8018b0fef30d6d1de798ce99cd05

**Comment by derekcollison** [comment] 2019-07-10 12:39
Thx

**Comment by derekcollison** [comment] 2019-07-10 12:43
Not sure of < 2.0 behavior if route interest was counted as well, but so far the test is doing what I expect.

**Comment by derekcollison** [comment] 2019-07-10 12:44
Meaning the varz subscriptions captures local subscriptions and remote interest from remote server subscriptions as well.

**Comment by ripienaar** [comment] 2019-07-10 12:45
I also tried to reproduce in isolation without a lot of success - it ticks up when viewed at hour resolutions not minutes. Annoying thing.

Is there a way via connz to view the remote interest?

**Comment by derekcollison** [comment] 2019-07-10 12:46
I don't think so.

**Comment by derekcollison** [comment] 2019-07-10 12:47
Question is should the varz just be showing total local subscriptions for all accounts and not remote interest here.

**Comment by derekcollison** [comment] 2019-07-10 12:48
@kozlovic do you have an opinion here, should varz/subscriptions show all subs, meaning local and all remote interest (binary meaning 0 or 1 for whole remote server per subject) or just local?

**Comment by ripienaar** [comment] 2019-07-10 12:48
![1 hour](https://i.imgur.com/GTTwLwu.png)

![1 hour](https://i.imgur.com/m9QSHX0.png)

machines are pretty busy and the rate of increase is not huge when viewed over a hour, so its one weird thing that triggers it and I have not been able to find it thinking about the maybe 20 different kind of traffic pattern i have

**Comment by ripienaar** [comment] 2019-07-10 12:49
local only makes sense to me, but I can see how the remote factors in, but if its not visible in things like connz I'd rather it doesnt show up :)

> Question is should the varz just be showing total local subscriptions for all accounts and not remote interest here.

**Comment by derekcollison** [comment] 2019-07-10 12:50
Does `connz?subs=1` show anything weird? Seems like regardless of the remote+local counting, you may have someone leaking subscriptions.

**Comment by ripienaar** [comment] 2019-07-10 12:53
nothing really stands out, I also confirmed that `subscriptions` stat per connection matches `len(subscriptions_list)` and that matches throughout.

Over my 3 snaps, the client list stayed static minus a few things I would expect and all have the subscription could i would expect (7 for each of the 7290)

**Comment by ripienaar** [comment] 2019-07-10 13:00
```json
{
  "server_id": "NBMQUFMTQL57PUYNSCV3RAQIMHRT7TSONJMKJWQ42L6OXX5D2W3JBFQ3",
  "now": "2019-07-10T12:59:40.571084532Z",
  "num_routes": 1,
  "routes": [
    {
      "rid": 7614,
      "remote_id": "NDBAAP2UM67NFI5I6VVLFHXW2V3VGVECUROHJ4QT2UOMJFV6D5VDFAK4"
      "did_solicit": true,
      "is_configured": true,
      "ip": "10.60.18.180",
      "port": 51460,
      "pending_size": 0,
      "in_msgs": 6265956,
      "out_msgs": 4013351,
      "in_bytes": 42887231547,
      "out_bytes": 8963606690,
      "subscriptions": 3791
    }
  ]
}
```

and on the other side:

```
$ curl -s http://localhost:6165/varz|jq .subscriptions
29429
```

**Comment by ripienaar** [comment] 2019-07-10 13:08
this makes sense the connected nodes (the 7k) each subscribe to 6 of the identical topics and 1 per unique.  So earlier we saw the remote cluster had 3657 clients connected, if each of those had a unique sub and the few others thats shared between them we'd get to the nubmer we see here in `subscriptions` on the remote route

**Comment by derekcollison** [comment] 2019-07-10 13:12
The Requests() will use a shared persistent wildcard _INBOX that is spun up on first Request invocation.

**Comment by derekcollison** [comment] 2019-07-10 13:13
So on a given machine, varz.subscriptions should equal sum([]connz.subscriptions) + sum([]routez.subscriptions)

**Comment by ripienaar** [comment] 2019-07-10 13:16
I'll confirm in a few

**Comment by derekcollison** [comment] 2019-07-10 18:37
Believe this is correct behavior. Reopen if not or there is a bug.

**Comment by ripienaar** [comment] 2019-07-10 18:41
Hmm, how do you reckon its correct behaviour when the subscription count grows forever but not shrink? Isnt the subscriptions count supposed to be a tally of current subscriptions?

My subscriptions are not increasing in total I add some and remove same a minute later, nothing subscribes for a long time over the 7k nodes - and those are 100% the same this DC doesnt get new machines.

There's no subscriptions being added that stays added - so the line shouldnt go up and up

**Comment by derekcollison** [comment] 2019-07-10 18:43
I wrote a test that showed the correct behavior. I asked if you could stop the client applications to show the drop but you said you could not. I can keep adding to the test if need be but without understanding exactly what all your apps are doing we can't discount an application leaking subscriptions.

**Comment by ripienaar** [comment] 2019-07-10 18:47
I said I will keep investigating tomorrow as I have been on 4 hours of calls and had no time to answer your question - but I dont think any of us have yet explained the problem, I will verify and answer your question tomorrow.

Regardless, total climbs and there is no reason it does since there is nothing making subscriptions.

**Comment by derekcollison** [comment] 2019-07-10 18:54
Will wait for more feedback from your tests.

**Comment by ripienaar** [comment] 2019-07-11 10:21
```
$ ./count.rb
connz subscriptions: 7038
routez subscriptions: 3847
combined subscriptions: 10885
varz subscriptions: 29344
varz != routez+connectionz, out by 18459
```

Script used to count here:

```ruby
require "json"

varz = JSON.parse(%x{curl -s http://localhost:6165/varz})
connz = JSON.parse(%x{curl -s http://localhost:6165/connz})
routez = JSON.parse(%x{curl -s http://localhost:6165/routez})

conntotal = connz["connections"].reduce(0) {|memo, c| memo + c["subscriptions"]}
routetotal = routez["routes"].reduce(0) {|memo, r| memo + r["subscriptions"]}
total = conntotal+routetotal

puts "connz subscriptions: %d" % conntotal
puts "routez subscriptions: %d" % routetotal
puts "combined subscriptions: %d" % total
puts "varz subscriptions: %d" % varz["subscriptions"]

if varz["subscriptions"] == total
  puts "varz == routes+connections"
else
  puts "varz != routez+connectionz, out by %d" % [(varz["subscriptions"] - total).abs]
end
```

**Comment by ripienaar** [comment] 2019-07-11 10:35
Instead of shutting down my clients - which I cant do - I firewalled them off the machines:

Machine1:

```
$ curl -s http://localhost:6165/varz|jq .connections
0
$ curl -s http://localhost:6165/varz|jq .subscriptions
177
$ curl -s http://localhost:6165/routez
....
    "subscriptions": 177
....
```

Machine 2:

```
$ curl -s http://localhost:6165/varz|jq .connections
0
$ curl -s http://localhost:6165/varz|jq .subscriptions
213
$ curl -s http://localhost:6165/routez
...
      "subscriptions": 213
...
```

Somethings not forgetting stuff when they should be forgetting them.

**Comment by derekcollison** [comment] 2019-07-11 13:31
Not sure we forget since it seems to become consistent when the client connections are removed.

These the only two machines or are their others? Any use of Gateways?

**Comment by ripienaar** [comment] 2019-07-11 13:32
only the 2 in a traditional cluster, no NATS 2 features like gateways of leafnodes or accounts in use - just a 1:1 upgrade in code from 1 to 2 and using just a cluster.

**Comment by derekcollison** [comment] 2019-07-11 13:43
Any slow consumers, routes being dropped and recreated?

**Comment by ripienaar** [comment] 2019-07-11 13:46
not seen any slow consumer logs

**Comment by derekcollison** [comment] 2019-07-11 13:49
ok and no system accounts either at this point?

**Comment by ripienaar** [comment] 2019-07-11 13:50
no account anything at all - which is a shame cos I would love to see whats in those system messages now :)

**Comment by ripienaar** [comment] 2019-07-11 13:52
One thing I think I will do tomorrow morning when i can afford the downtime again is:

1) firewall everything off
2) firewall off the cluster port between the two
3) reopen the cluster port and tcpdump the cluster traffic.

Then I will know what these few 100 subscriptions are as they will propagate their interest again on cluster rejoin.

**Comment by derekcollison** [comment] 2019-07-11 13:53
Try `/subsz?subs=1`

**Comment by ripienaar** [comment] 2019-07-11 14:02
I'll check that out when I have them without subscribers again tomorrow - now I do not notice anything weird, but I wouldnt be able to tell a normal looking subscription thats active from one thats orphaned without draining the traffic.

**Comment by derekcollison** [comment] 2019-07-11 14:08
ok to quickly summarize, the math part is working correctly, meaning that `varz == routes+connections` but we seem to have subscriptions on the routes that do not clear when all client connections go to zero, that a fair assessment?

**Comment by derekcollison** [comment] 2019-07-11 14:18
IIRC `subsz` should show you all, hopefully the orphaned ones too.

**Comment by ripienaar** [comment] 2019-07-11 14:25
> ok to quickly summarize, the math part is working correctly, meaning that `varz == routes+connections` but we seem to have subscriptions on the routes that do not clear when all client connections go to zero, that a fair assessment?

yes, that looks to be where we are getting to via process of elimination.  On another test DC - though 1/7 the size - I have only one unclustered NATS 2 based broker and this one does not exhibit this behaviour so further pointing at it being cluster code related.

**Comment by ripienaar** [comment] 2019-07-12 08:52
Well, thats annoying.  I kept the firewalls up a bit longer as I had a call and after a 30 minutes disconnection between the cluster members subscriptions reset to 0.  That is connections was 0, subscriptions was 60ish and after 30 minutes when I was about to investigate what they are they had dropped to 0.  So I missed it and now the problem is for the moment gone.

Lets leave it open in a day I'll have take another look and try to catch it once its had time to build up again.

**Comment by derekcollison** [comment] 2019-07-12 14:46
ok thanks.

**Comment by ripienaar** [comment] 2019-07-15 09:45
I tried a different approach today, appears that dropping the cluster connection to try and get it to send them across the wire again zeros out the problem.

Also its not shown in subsz

```
$ curl "http://localhost:6165/subsz?subs=1&limit=100000"
{
  "num_subscriptions": 4,
  "num_cache": 62811,
  "num_inserts": 125359,
  "num_removes": 125355,
  "num_matches": 11338570,
  "cache_hit_rate": 0.17701632569186415,
  "max_fanout": 0,
  "avg_fanout": 0
}

Other one the same

**Comment by derekcollison** [comment] 2019-07-15 16:30
Feels to me we may have some accounting issues that present in edge case scenarios. Will keep digging.

**Comment by ripienaar** [comment] 2019-07-15 17:51
Memory profiling have the ring buffer come up much bigger than I would anticipate, I don’t think it’s really used in my case. 

I don’t really grok pprof so well though so I could (probably am) reading things wrong.

**Comment by derekcollison** [comment] 2019-07-15 17:54
ring buffer is to hold last N closed connections for inspection.

**Comment by ripienaar** [comment] 2019-07-15 17:55
Yes and defaults to 10 connections iirc now. But pprof show it several MB big. 

But I couldn’t tell how the way it’s wrote will every lead to what we see though :(

**Comment by derekcollison** [comment] 2019-07-15 17:57
10k is default IIRC>

**Comment by ripienaar** [comment] 2019-07-15 17:59
Ah! Big miss read on my part :) will look at disabling that

**Comment by derekcollison** [comment] 2019-07-15 18:41
It is an option so you can change it, but should not take up too much room IMO..

**Comment by ripienaar** [comment] 2019-07-18 11:31
So I kept everything else the same - same client software, same traffic patterns etc - I just shut the cluster down and brought up only one node of the cluster.  Everything else stayed the same.

Here the drop is when I restarted all on one node - the drop is the leak being cleared on restart.

![clustered vs unclustered](https://i.imgur.com/fUTTJ9J.png)

While clustered I am seeing the connection leak, while unclustered things stay stable.

Likewise with the memory profile

![clustered vs unclustered](https://i.imgur.com/nYVlXot.png)

Unclustered shortly after start I see this from a memory profile capture:

```
(pprof) top5
Showing nodes accounting for 151.74MB, 79.97% of 189.76MB total
Dropped 39 nodes (cum <= 0.95MB)
Showing top 5 nodes out of 52
      flat  flat%   sum%        cum   cum%
   45.95MB 24.21% 24.21%    49.62MB 26.15%  github.com/choria-io/go-choria/vendor/github.com/nats-io/nats-server/v2/server.(*Server).createClient
   42.72MB 22.51% 46.73%    42.72MB 22.51%  math/rand.NewSource
   36.78MB 19.38% 66.11%   125.50MB 66.14%  github.com/choria-io/go-choria/vendor/github.com/nats-io/nats-server/v2/server.(*client).readLoop
   13.56MB  7.15% 73.25%    13.56MB  7.15%  github.com/choria-io/go-choria/vendor/github.com/nats-io/nats-server/v2/server.(*client).queueOutbound
   12.74MB  6.71% 79.97%    18.24MB  9.61%  github.com/choria-io/go-choria/vendor/github.com/nats-io/nats-server/v2/server.(*Sublist).Insert
```

After running for 19 hours:

```
(pprof) top5
Showing nodes accounting for 208.17MB, 83.04% of 250.68MB total
Dropped 40 nodes (cum <= 1.25MB)
Showing top 5 nodes out of 47
      flat  flat%   sum%        cum   cum%
   62.85MB 25.07% 25.07%    62.85MB 25.07%  github.com/choria-io/go-choria/vendor/github.com/nats-io/nats-server/v2/server.(*client).queueOutbound
   45.95MB 18.33% 43.40%    48.62MB 19.39%  github.com/choria-io/go-choria/vendor/github.com/nats-io/nats-server/v2/server.(*Server).createClient
   43.91MB 17.52% 60.92%   182.93MB 72.97%  github.com/choria-io/go-choria/vendor/github.com/nats-io/nats-server/v2/server.(*client).readLoop
   42.72MB 17.04% 77.96%    42.72MB 17.04%  math/rand.NewSource
   12.74MB  5.08% 83.04%    18.24MB  7.27%  github.com/choria-io/go-choria/vendor/github.com/nats-io/nats-server/v2/server.(*Sublist).Insert
```

However doing the same with the clustered scenario, I see significant growth that isnt seen unclustered:

At start:

````
(pprof) top5
Showing nodes accounting for 162.64MB, 77.79% of 209.07MB total
Dropped 70 nodes (cum <= 1.05MB)
Showing top 5 nodes out of 42
      flat  flat%   sum%        cum   cum%
   52.32MB 25.03% 25.03%    58.50MB 27.98%  github.com/choria-io/go-choria/vendor/github.com/nats-io/nats-server/v2/server.(*Server).createClient
   44.73MB 21.39% 46.42%    44.73MB 21.39%  math/rand.NewSource
   39.70MB 18.99% 65.41%    39.70MB 18.99%  github.com/choria-io/go-choria/vendor/github.com/nats-io/nats-server/v2/server.(*client).queueOutbound
   13.50MB  6.46% 71.87%    23.14MB 11.07%  github.com/choria-io/go-choria/vendor/github.com/nats-io/nats-server/v2/server.(*client).processSub
   12.39MB  5.92% 77.79%    14.89MB  7.12%  github.com/choria-io/go-choria/vendor/github.com/nats-io/nats-server/v2/server.(*Sublist).Insert
````

After 20ish hours:

```
(pprof) top5
Showing nodes accounting for 284.77MB, 81.74% of 348.39MB total
Dropped 42 nodes (cum <= 1.74MB)
Showing top 5 nodes out of 34
      flat  flat%   sum%        cum   cum%
  118.42MB 33.99% 33.99%   118.42MB 33.99%  github.com/choria-io/go-choria/vendor/github.com/nats-io/nats-server/v2/server.(*client).queueOutbound
   75.97MB 21.81% 55.80%    81.14MB 23.29%  github.com/choria-io/go-choria/vendor/github.com/nats-io/nats-server/v2/server.(*Server).createClient
   62.82MB 18.03% 73.83%    62.82MB 18.03%  math/rand.NewSource
      18MB  5.17% 79.00%    25.07MB  7.19%  github.com/choria-io/go-choria/vendor/github.com/nats-io/nats-server/v2/server.(*client).processSub
    9.55MB  2.74% 81.74%   244.62MB 70.21%  github.com/choria-io/go-choria/vendor/github.com/nats-io/nats-server/v2/server.(*client).readLoop
```

**Comment by derekcollison** [comment] 2019-07-18 19:38
Thanks.

What is best way to recreate on our side? Just high level patterns of what you are doing etc. Connections coming and going, subs, requests etc?

**Comment by ripienaar** [comment] 2019-07-19 10:04
I have 7k clients with 6 subscriptions each, 5 of these are used for 1:n and 1 of them for 1:1 - in other words all 7k would subscribe to the same 5 and each client of the 7k would have a unique subscription just for that one.  These are long running and dont disconnect/reconnect unless the machine reboots or we do maintenance etc - almost none of that in this test data

Example:

```
      "subscriptions_list": [
        "mcollective.broadcast.agent.rpcutil",
        "mcollective.broadcast.agent.choria_util",
        "mcollective.broadcast.agent.om",
        "mcollective.broadcast.agent.provisioning",
        "mcollective.broadcast.agent.acme",
        "mcollective.node.fqdn",
      ]
```

Here the broadcast ones are 1:n and every node subscribe to them and the fqdn one is unique to this node.

Each of the 7k publish data (10kbish) to a topic and there is a queue group of maybe 20 subscribers on that topic receiving data off it and processing it.

I then have regular clients that connect and these clients make 1 or 4 connections and they subscribe to a unique inbox and then publish data into sometimes the 1:1 and many times into the 1:n, they wait for a replies - sometimes from the full 7k sometimes a subset - directed at their inbox and disconnect. These are usually short lived - seconds to minutes.

That's about it, its not really very weird or unusual patterns.  I will this weekend try to make something in a docker compose cluster that reproduce the problem.

**Comment by derekcollison** [comment] 2019-07-19 14:22
Thanks that is helpful.

**Comment by ripienaar** [comment] 2019-07-20 17:19
Getting nearer to being able to reproduce this - but just wanted to say i was able to get this to happen with stock github downloaded release 2.0.2 running outside of my embedded code.

A request to `/routez?subs=1` shows one of my reply queues is being orphaned in the route `subscriptions_list`

**Comment by derekcollison** [comment] 2019-07-21 01:28
ok thanks. Its probably an edge condition but would love to track it down and fix it for sure.

**Comment by ripienaar** [comment] 2019-07-21 05:51
Yeah real pain. As it have associated memory growth I can’t move to 2 :(

**Comment by ripienaar** [comment] 2019-07-21 13:24
Code below when run against a cluster for a few hours will cause orphans to show up in `/routez?subs=1` 

cluster is started with `nats-server --routes nats://br1.example.net:5222,nats://br2.example.net:5222 --cluster nats://br1.example.net:5222 -m 8222` and its official 2.0.2 version

The code below is run like:

```
while true
do 
  BROKER=nats://br1.example.net:4222,nats://br2.example.net:4222 WAITFOR=10 req
done
```

with 10 x `nats-rply -s nats://br1.example.net:4222 test '{"sender":"node2"}'` spreading these across the cluster and where nats-rply is the one from the examples directory in go.nats

The code below is the result of trying random bad things that I imagine could happen in my scenario and eventually I caught this caused it, there might well be a much simpler way to reproduce but this works.  The code deliberately causes client slow consumers by making the receive channel too small (though honestly I am not sure why a 1 buffered chan is going to cause slow consumers maybe you can explain) - anyway, so client slow consumers and bad client closes and just running many of these for hours, you'll eventually see orphaned subs.

I tried recreating using the normal nats-req in your examples but couldnt, so made this awful code with 4 subscriptions multiplexing the replies and forced slow consumer errors.

I run the brokers and clients and all in docker compose - its shitty networking seem to also contribute :P

```golang
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"math/rand"
	"os"
	"strconv"
	"time"

	"github.com/nats-io/nats.go"
)

var letterRunes = []rune("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ")

func panicIfErr(err error) {
	if err != nil {
		panic(err)
	}
}

func uniqueID() (id string) {
	b := make([]rune, 32)
	for i := range b {
		b[i] = letterRunes[rand.Intn(len(letterRunes))]
	}

	return string(b)
}

func connAndSubscribe(grp, inbox string, c chan (*nats.Msg)) {
	opts := []nats.Option{
		nats.ErrorHandler(func(nc *nats.Conn, sub *nats.Subscription, err error) {
			fmt.Printf("NATS client on %s encountered an error: %s\n", nc.ConnectedUrl(), err)
		}),
	}
	conn, err := nats.Connect(os.Getenv("BROKER"), opts...)
	panicIfErr(err)

	_, err = conn.ChanQueueSubscribe(inbox, grp, c)
	panicIfErr(err)
}

func main() {
	waitfor, err := strconv.Atoi(os.Getenv("WAITFOR"))
	panicIfErr(err)

	conn, err := nats.Connect(os.Getenv("BROKER"))
	panicIfErr(err)

	ctx, cancel := context.WithTimeout(context.Background(), 1*time.Second)
	defer cancel()

	grp := uniqueID()
	msgs := make(chan *nats.Msg, 1)
	inbox := fmt.Sprintf("%s.reply.%s.%s", "testing", "samplesender", grp)

	connAndSubscribe(grp, inbox, msgs)
	connAndSubscribe(grp, inbox, msgs)
	connAndSubscribe(grp, inbox, msgs)
	connAndSubscribe(grp, inbox, msgs)

	ctr := 0
	payload := ""
	for i := 0; i < 5*1024; i++ {
		payload = payload + fmt.Sprintf("%d", i%10)
	}

	fmt.Printf("publishing with reply queue %s\n", inbox)
	conn.PublishMsg(&nats.Msg{
		Data:    []byte(payload),
		Subject: "test",
		Reply:   inbox,
	})

	for {
		select {
		case msg := <-msgs:
			var dat map[string]string

			err := json.Unmarshal(msg.Data, &dat)
			panicIfErr(err)
			fmt.Printf("%d received msg %d from %s\n", os.Getpid(), ctr, dat["sender"])

			ctr++
			if ctr >= waitfor {
				return
			}
		case <-ctx.Done():
			fmt.Printf("Timeout waiting for responses\n")
			return
		}
	}
}
```

**Comment by ripienaar** [comment] 2019-07-21 13:39
Example, with all instances of above code dead, subs remain forever:

```
      "subscriptions_list": [
        "test",
        "testing.reply.samplesender.wsGUIQJufEboWBGaGXzjAdNqoCAtmdJc"
      ]
```

**Comment by derekcollison** [comment] 2019-07-21 16:37
ok great I will take a look today. We will get it fixed.

**Comment by derekcollison** [comment] 2019-07-21 18:03
Can you tell if the route was ever a slow consumer and was dropped and reconnected?

**Comment by ripienaar** [comment] 2019-07-21 18:05
No. Previously I tried dropping it and that cleared the orphans. Not tried same this time

**Comment by derekcollison** [comment] 2019-07-21 18:14
ok thanks.

**Comment by derekcollison** [comment] 2019-07-21 22:16
ok I have reproduced in a test. Will work on fix now.

**Comment by derekcollison** [comment] 2019-07-22 02:45
I tracked down the issue and applied a brute force fix to make the tests pass. However this fix is not suitable for real code, I just hold a lock longer to synchronize some things to test my theory. It will cause a deadlock so need to come up with a better way. Will work on that tomorrow.

**Comment by derekcollison** [comment] 2019-07-23 16:41
Confirm when you have a chance that this fixes your issue. Will leave open until then.

**Comment by ripienaar** [comment] 2019-07-24 10:52
I have updated my side, lets give it a day or 2 to be sure

**Comment by ripienaar** [comment] 2019-07-24 10:58
cant imagine your fix would have made things faster reading it, but performance is off the charts, this is a request/response with 1:n fanout on the request, 7k responses in 500ms is amazing.

```
$ choria ping
---- ping statistics ----
7327 replies max: 546.45 min: 38.93 avg: 258.15
```

**Comment by derekcollison** [comment] 2019-07-24 14:40
The issue that was presenting was that interest in a queue subscriber was changing quickly across multiple connections. That order or change was not being preserved across a route so you could see things out of order, for instance unsubscribe followed by a subscribe of N, even though the original order was 3,2,1,RS- (Unsubscribe). The fix in guaranteeing order was also to realize that we only needed the last proper value for the queue weight to be sent, so we probably reduced alot of interest graph traffic as well for your specific use case.

**Comment by ripienaar** [comment] 2019-07-25 06:45
We're good on this one wrt the subscriptions, I still see memory growth - less - but its still there and its about queueOutbound mainly, let me keep an eye on that and I'll open a new issue tomorrow after I got some memory profile dumps now

**Comment by derekcollison** [comment] 2019-07-25 06:55
Ok thx for the update.


________________________________

**Comment by derekcollison** [comment] 2019-07-25 14:50
Closing this one and using #1082 moving forward for the memory issues.

**Closed by derekcollison** 2019-07-25 14:50 UTC
