### ISSUE TITLE
WebSocket Connection Questions.

### ISSUE THREAD

**Issue by byazrail** [nats-io/nats-server#2503] opened 2021-09-09 14:02 UTC
Hello there,

I am using Nats Server 2.4.0.
I've been using ws-tcp-relay and isobit/websocket-nats websocket integration for a long time.

I installed Nats Server 2.4.0 today.
Incoming requests come as binary.
Outgoing requests from the band go as json.
How can I make outgoing requests from me binary?

I also checked your nats.ws project, but it is available as nodejs.
Not for normal browser use I guess I still use isobit/websocket-nats for browsers.

I've attached an image for the binary examples.
The answers I get are binary.
Outgoing requests from me are json.

<img width="1090" alt="Screen Shot 2021-09-09 at 16 56 20" src="https://user-images.githubusercontent.com/5870455/132700260-4b2f0ceb-6aeb-451d-9be1-d2a740be5d43.png">

**Comment by aricart** [comment] 2021-09-09 15:52
duplicate of https://github.com/nats-io/nats.ws/issues/111

**Closed by aricart** 2021-09-09 15:52 UTC
