### ISSUE TITLE
KV Get/Watch fails even though key/value is present

### ISSUE THREAD

**Issue by anthonyjacques20** [nats-io/nats-server#4643] opened 2023-10-10 00:18 UTC
### What version were you using?

`2.10.1`

### What environment was the server running in?

Docker image `2.10.1` was where we originally saw it but able to reproduce it running `nats-server` binary directly on mac M2

### Is this defect reproducible?

Yes the overall issue is reproducible but the specific keys that are erroring is not the same every time.

1. nats-server `2.9.21` running in production (for months)
2. `nats stream backup` (or `nats account backup`, both appeared to cause the same problem)
3. Spin up brand new nats-server `2.10.1`
4. `nats stream restore` (or `nats account restore`) with the data from the old server to the new server
5. Change number of history values in the `kv` with `nats stream edit {bucket} --max-msgs-per-subject=1`
6. We have one KV that is pretty large (~3GB) and we were getting `nats key not found` errors for keys that we know are in the KV
7. The following were ways that we _could_ access the data:
* `nats kv ls {bucket}` would include the "missing" key
* `nats kv history {bucket} {key}` would show the "missing" key where the last entry was a `PUT` (see screenshot)
* `nats kv get {bucket} {key} --revision={revision}`
8. The following did **not** work:
* `nats kv get {bucket} {key}` would give `nats key not found` errors
* `nats kv watch {bucket} {key}`

Some notes:
* Once the server was in this "error" state, the `nats kv get` would fail every time, it wasn't intermittent
* Unable to provide the backups that caused this due to data contents (redacted some info in screenshot)
* This only happened to _some_ of the keys, it wasn't _every_ key
![NatsKVGetFailure](https://github.com/nats-io/nats-server/assets/12755023/289848b3-6373-471e-ac9b-1959ddc53a5a)

### Given the capability you are leveraging, describe your expectation?

We expect that a `KV Get` would return the value stored in that key.

### Given the expectation, what is the defect you are observing?

Some of the keys were showing `nats key not found` error even though the following were true:
* `nats kv ls` showed the key in list
* `nats kv history {bucket} {key}` showed the last entry was a `PUT` (so it should exist)
* `nats kv get {bucket} {key} --revision={revision}` returned correct value

**Comment by anthonyjacques20** [comment] 2023-10-10 00:19
Also worth noting that I used `nats cli` as an example in the bug but we were seeing the same behavior from the `go client`, so I don't think it's specific to the `nats cli`

**Comment by ripienaar** [comment] 2023-10-10 04:46
What version CLI? And if next time this happens can you please do the failing get with —trace

**Comment by ripienaar** [comment] 2023-10-10 04:52
And I assume the backup/restore step is essential?

Also be good to see “nats stream info KV_X” for this bucket

**Comment by anthonyjacques20** [comment] 2023-10-10 05:04
CLI version `0.1.1`
Response with --trace:
```
➜  ~ nats kv get redactedKV_tasks redactedKey416 --trace
21:59:10 >>> $JS.API.STREAM.INFO.KV_redactedKV_tasks


21:59:10 <<< $JS.API.STREAM.INFO.KV_redactedKV_tasks: {"type":"io.nats.jetstream.api.v1.stream_info_response","total":0,"offset":0,"limit":0,"config":{"name":"KV_redactedKV_tasks","subjects":["$KV.redactedKV_tasks.\u003e"],"retention":"limits","max_consumers":-1,"max_msgs":-1,"max_bytes":-1,"max_age":31536000000000000,"max_msgs_per_subject":1,"max_msg_size":10485760,"discard":"new","storage":"file","num_replicas":1,"duplicate_window":120000000000,"compression":"none","allow_direct":false,"mirror_direct":false,"sealed":false,"deny_delete":true,"deny_purge":false,"allow_rollup_hdrs":true,"consumer_limits":{}},"created":"2023-10-09T18:10:30.633892418Z","state":{"messages":38499,"bytes":2398690589,"first_seq":21581133,"first_ts":"2023-10-09T14:10:10.756704868Z","last_seq":21752102,"last_ts":"2023-10-09T18:21:24.722858277Z","num_subjects":38492,"num_deleted":132471,"consumer_count":0},"cluster":{"leader":"NCZ4QAQW6SOSN57AZODVQBLWFDGKFQ3U34QG6KWXIG5PFNLZSO3DTJVP"},"ts":"2023-10-10T04:59:10.012146Z"}
21:59:10 >>> $JS.API.STREAM.MSG.GET.KV_redactedKV_tasks
{"last_by_subj":"$KV.redactedKV_tasks.redactedKey416"}

21:59:10 <<< $JS.API.STREAM.MSG.GET.KV_redactedKV_tasks: {"type":"io.nats.jetstream.api.v1.stream_msg_get_response","error":{"code":404,"err_code":10037,"description":"no message found"}}
nats: error: nats: key not found
```

Not 100% sure if the backup/restore step is essential. But this is the only time we've seen it. It might be possible that this is more related to the fact that we altered the `max-msgs-per-subject` and the backup/restore is unrelated. Not sure but I'll do more troubleshooting tomorrow.

**Comment by anthonyjacques20** [comment] 2023-10-10 05:05
And the `nats stream info`:
```
➜  ~ nats stream info KV_redactedKV_tasks
Information for Stream KV_redactedKV_tasks created 2023-10-09 11:10:30

              Subjects: $KV.redactedKV_tasks.>
              Replicas: 1
               Storage: File

Options:

             Retention: Limits
       Acknowledgments: true
        Discard Policy: New
      Duplicate Window: 2m0s
     Allows Msg Delete: false
          Allows Purge: true
        Allows Rollups: true

Limits:

      Maximum Messages: unlimited
   Maximum Per Subject: 1
         Maximum Bytes: unlimited
           Maximum Age: 1y0d0h0m0s
  Maximum Message Size: 10 MiB
     Maximum Consumers: unlimited

State:

              Messages: 38,499
                 Bytes: 2.2 GiB
        First Sequence: 21,581,133 @ 2023-10-09 07:10:10 UTC
         Last Sequence: 21,752,102 @ 2023-10-09 11:21:24 UTC
      Deleted Messages: 132,471
      Active Consumers: 0
    Number of Subjects: 38,492
```

**Comment by ripienaar** [comment] 2023-10-10 05:08
Thanks a lot. 

If this is a throw away test environment you can try enabling Direct Get on  stream with stream edit and see if it helps (again show trace please)

**Comment by anthonyjacques20** [comment] 2023-10-10 17:08
@ripienaar - sure thing, didn't seem to make a difference:
```
➜  ~ nats stream edit KV_redactedKV_tasks --allow-direct
Differences (-old +new):
  api.StreamConfig{
  	... // 24 identical fields
  	DenyPurge:     false,
  	RollupAllowed: true,
- 	AllowDirect:   false,
+ 	AllowDirect:   true,
  	MirrorDirect:  false,
  	DiscardNewPer: false,
  	... // 2 identical fields
  }
? Really edit Stream KV_redactedKV_tasks Yes
Stream KV_redactedKV_tasks was updated

Information for Stream KV_redactedKV_tasks created 2023-10-09 11:10:30

              Subjects: $KV.redactedKV_tasks.>
              Replicas: 1
               Storage: File

Options:

             Retention: Limits
       Acknowledgments: true
        Discard Policy: New
      Duplicate Window: 2m0s
            Direct Get: true
     Allows Msg Delete: false
          Allows Purge: true
        Allows Rollups: true

Limits:

      Maximum Messages: unlimited
   Maximum Per Subject: 1
         Maximum Bytes: unlimited
           Maximum Age: 1y0d0h0m0s
  Maximum Message Size: 10 MiB
     Maximum Consumers: unlimited

State:

              Messages: 38,499
                 Bytes: 2.2 GiB
        First Sequence: 21,581,133 @ 2023-10-09 07:10:10 UTC
         Last Sequence: 21,752,102 @ 2023-10-09 11:21:24 UTC
      Deleted Messages: 132,471
      Active Consumers: 0
    Number of Subjects: 38,492
➜  ~ nats kv get redactedKV_tasks redactedKey416 --trace
10:06:45 >>> $JS.API.STREAM.INFO.KV_redactedKV_tasks


10:06:45 <<< $JS.API.STREAM.INFO.KV_redactedKV_tasks: {"type":"io.nats.jetstream.api.v1.stream_info_response","total":0,"offset":0,"limit":0,"config":{"name":"KV_redactedKV_tasks","subjects":["$KV.redactedKV_tasks.\u003e"],"retention":"limits","max_consumers":-1,"max_msgs":-1,"max_bytes":-1,"max_age":31536000000000000,"max_msgs_per_subject":1,"max_msg_size":10485760,"discard":"new","storage":"file","num_replicas":1,"duplicate_window":120000000000,"compression":"none","allow_direct":true,"mirror_direct":false,"sealed":false,"deny_delete":true,"deny_purge":false,"allow_rollup_hdrs":true,"consumer_limits":{}},"created":"2023-10-09T18:10:30.633892418Z","state":{"messages":38499,"bytes":2398690589,"first_seq":21581133,"first_ts":"2023-10-09T14:10:10.756704868Z","last_seq":21752102,"last_ts":"2023-10-09T18:21:24.722858277Z","num_subjects":38492,"num_deleted":132471,"consumer_count":0},"cluster":{"leader":"NCZ4QAQW6SOSN57AZODVQBLWFDGKFQ3U34QG6KWXIG5PFNLZSO3DTJVP"},"ts":"2023-10-10T17:06:45.741923Z"}
10:06:45 >>> $JS.API.DIRECT.GET.KV_redactedKV_tasks.$KV.redactedKV_tasks.redactedKey416


10:06:45 <<< $JS.API.DIRECT.GET.KV_redactedKV_tasks.$KV.redactedKV_tasks.redactedKey416:
nats: error: nats: key not found
```

**Comment by ripienaar** [comment] 2023-10-10 18:04
All right thanks, i tried to do a few things to reproduce and so far no luck.  Difficult one for sure.

**Comment by aricart** [comment] 2023-10-10 18:13
While there's no mention of republish - depending on the source of the message, it could be a duplicate of https://github.com/nats-io/nats.deno/issues/586

**Closed** 2023-10-12 19:30 UTC
Labels: defect
