### ISSUE TITLE
jetstream could not pull message after nats-server restart

### ISSUE THREAD

**Issue by carr123** [nats-io/nats-server#2397] opened 2021-08-03 01:57 UTC
i was testing jetstream on nats-server v2.3.2.  one sender and one receiver program are running  for quite a long time.

this is what my stream look like :

```go
	_, err = js.AddStream(&nats.StreamConfig{
		Name:      streamName,
		Subjects:  []string{streamSubjects},
		Storage:   nats.FileStorage,
		Replicas:  3,
		Retention: nats.WorkQueuePolicy,
		Discard:   nats.DiscardNew,
		MaxMsgs:   -1,
		MaxAge:    time.Hour * 24 * 365,
	})
```

this is how i create the consumer:

```go
	if _, err := js.AddConsumer(streamName, &nats.ConsumerConfig{
		Durable:       durableName,
		DeliverPolicy: nats.DeliverAllPolicy,
		AckPolicy:     nats.AckExplicitPolicy,
		ReplayPolicy:  nats.ReplayInstantPolicy,
		FilterSubject: subjectName,
		AckWait:       time.Second * 30,
		MaxDeliver:    -1,
		MaxAckPending: 1000,
	}); err != nil && !strings.Contains(err.Error(), "already in use") {
		log.Println("AddConsumer fail")
		return
	}
```

this is what the subscriber look like:

```go
	sub, err := js.PullSubscribe("ORDERS.created", durableName, nats.Bind("ORDERS", durableName))
	if err != nil {
		fmt.Println(" PullSubscribe:", err)
		return
	}
       msgs, err := sub.Fetch(1000, nats.MaxWait(10*time.Second))
```      

when i restart my nats-server cluster nodes(upgrade to nats-server 2.3.3), 
the consumer can no longer pull messages even if i restart my consumer program. 
the Fetch call just return : "nats: timeout", but i'm sure there are lots of message in the working queue.
only if i delete the consumer by calling js.DeleteConsumer(streamName, durableName),  recreate it, my program can 
resume fetching messages.
actually, every time i restart nats-server nodes, my consumer program encouter the same problem.

there is another issue, after i restart nats-server nodes,  restart my program, it sometimes reports : "PullSubscribe: nats: JetStream system temporarily unavailable"

I expect nats-server nodes restarting action not impacting jetstream clients fetching messages.

**Comment by carr123** [comment] 2021-08-03 03:24
reproduce this issue:
1. start a client program fetching messages in a loop
2. make sure there are NO messages in the jetsteam
2. restart each nats-server cluster node one by one.
3. send some messages to jetstream system
4. you can notice the former consumer client can not fetch any messages even restart it.

**Comment by derekcollison** [comment] 2021-08-03 04:02
Just to confirm this is with current 2.3.3 release yes?

**Comment by carr123** [comment] 2021-08-03 04:11
> Just to confirm this is with current 2.3.3 release yes?

i test it on v2.3.3.  i guess former nats-server version has the same problem.  
i saw the bug weeks ago, i didn't know how to reproduce it, otherwise i would have reported it.

**Comment by derekcollison** [comment] 2021-08-03 04:22
Will see what @wallyqs or @variadico can come up with.

**Comment by wallyqs** [comment] 2021-08-03 05:45
@carr123 you can try the following helper to wait for JS to be ready when it is temporarily unavailable due to a restart: https://github.com/nats-io/nats.go/blob/master/test/js_test.go#L4311-L4328
In some of the restart tests and you could for example back off when get either a 503 or timeout before retrying: https://github.com/nats-io/nats.go/blob/master/test/js_test.go#L5527-L5537

**Comment by carr123** [comment] 2021-08-03 07:27
@wallyqs hi, i add some sleep codes, it seems bring no difference.

	sub, err := js.PullSubscribe("ORDERS.created", durableName, nats.Bind("ORDERS", durableName))
	if err != nil {
		fmt.Println("PullSubscribe fail:", err)
		return
	}
	
	for {
		if !sub.IsValid() {
			log.Println("sub invalid !!!")
			return
		}
	
		msgs, err := sub.Fetch(1000, nats.MaxWait(10*time.Second))
		if err == nats.ErrNoResponders || err == nats.ErrTimeout {
			log.Println("Fetch fail 1:", err)
			time.Sleep(100 * time.Millisecond)
			continue
		}

		if err != nil {
			log.Println("Fetch fail 2:", err)
			return
		}

		for _, msg := range msgs {
			msg.Ack()
			log.Println("recv data:", string(msg.Data))
		}
	}

i still get "Fetch fail 1: nats: timeout"  while there are messages in the working queue, no matter how long i wait or how many times i restart my client program.
only  adding  "js.DeleteConsumer()"  before "js.AddConsumer()", then restarting my program can work.
it seems something is wrong in the Consumer state on the nats-server side. creating a new consumer will continue fetching messages.

**Comment by carr123** [comment] 2021-08-05 00:42
my nats-server 3 nodes cluster just upgrade to v2.3.4 from v2.3.3, problem still there. even worse.
after i replace and restart nats-server binary for all 3 nodes, i sent some messages to jsm working queue for testing purpose.
my client program failed to fetch messages from now on.
i quit and restart my client program , the js.PullSubscribe reports error: "nats: JetStream system temporarily unavailable", it stays 
"unavailable" for a couple of minutes, and seems never become available.
i had to use my final solution, calling js.DeleteConsumer() before js.AddConsumer(),  then JetStream become available,  js.PullSubscribe succeeded. fetch operation can work too, all messages are fetched and removed from server.
i sent more messages, all are then consumed as expected.

**Comment by derekcollison** [comment] 2021-08-05 00:49
Which Go client version are you using? Maybe you and @wallyqs can sync up.

**Comment by carr123** [comment] 2021-08-05 02:02
client program, go version go1.16.6
"github.com/nats-io/nats.go"  use the latest code, downloaded few minutes age.
nats-server v2.3.4

here are the testing results:
1. no matter how many messages are there in jsm before nats-servers restart,
   client can not resume fetching messages. 
2. "nats: JetStream system temporarily unavailable", this error doesn't always appear every time i perform nats-server restart tests. sometimes when it is  unavailable, it seems not temporarily but permantly.
3. consumer recreation can solve above 2 problems
4. it seems consumer infomation on the server side not resilient to cluster restart

**Comment by wallyqs** [comment] 2021-08-05 17:49
@carr123 could you share a runnable example gist to try to reproduce? That would help narrowing down the issue you are running into 🙏

**Comment by kozlovic** [comment] 2021-08-05 18:56
Also, for v2.3.4, we wrote a test trying to reproduce the exact same steps you have described in the first comment of this report. Please have a look at https://github.com/nats-io/nats-server/blob/7112ae06a54899471910c82a7edaf068040f6dae/server/jetstream_cluster_test.go#L7763 and see if that represents pretty well your scenario. This tests passes, so clearly there is something different in your environment.

When you see the problem, I would suggest that you run `nats c info` and then select the existing stream/consumer and post the output to see if there is something unusual. Other outputs that may be of interest:
`nats c report`, `nats s report`. Also `nats server report jetstream` (for this one, you need to specify a user from the system account (if you have one) using `nats -s nats://<system user>:<password>:<a host>:<port> server report jetstream`.

Finally, I would recommend that you setup various callbacks in the NATS connection to track when it gets disconnected, if it gets async errors or completely closed and you may not know about it. Example on how to set those callbacks can be seen [here](https://github.com/nats-io/nats.go/blob/91bdffe39f4143f12ee6c0531d23bb98393bef47/examples/nats-sub/main.go#L125).

**Comment by carr123** [comment] 2021-08-06 03:09
@wallyqs @kozlovic   

hello, this is my testing code and cluster config.

https://github.com/carr123/natsjsmdemo

**Comment by derekcollison** [comment] 2021-08-06 03:28
Thanks will take a look in morning.

**Comment by derekcollison** [comment] 2021-08-07 20:55
I took a look and updated the Go client underneath the server and double checked that the test @kozlovic wrote matches what your program is doing and that test passes 100%.

So, something about your setup is different or alluding us for some reason.

**Comment by derekcollison** [comment] 2021-08-07 20:57
Can you try removing the permission blocks that are empty? 

https://github.com/carr123/natsjsmdemo/blob/main/nats1.conf#L21
https://github.com/carr123/natsjsmdemo/blob/main/nats1.conf#L38

**Comment by derekcollison** [comment] 2021-08-07 20:59
That config is trying to express and "allow" block, meaning what the users can publish and subscribe to. Without any permissions you can do everything, what your block is saying is those users can **not** publish or subscribe to anything.

**Comment by carr123** [comment] 2021-08-09 02:51
@derekcollison i follow your instruction, remove the "permission " block.   problem still there.

**Comment by derekcollison** [comment] 2021-08-09 14:29
ok something then we are missing that is different with your setup then any of our tests etc.

Will ask @wallyqs and @variadico to try to schedule some time to get on a video call with you and walk through what you are seeing.

**Comment by wallyqs** [comment] 2021-08-09 16:23
Hello @carr123 could you DM me in Slack to setup something to take a look? https://slack.nats.io/

**Comment by carr123** [comment] 2021-08-10 01:09
@wallyqs i'm living in asia, maybe different timezone from you.  :)   
i test it in my office at work time, there's no camera available, and i have no access to slack possibly due to company's network security policy.
if you want to install some tool in my environment, just give me a download link.
if you want too see how i perform the test, i will make a video recording later.
thanks.

**Comment by derekcollison** [comment] 2021-08-10 02:10
Video would be great, including all setup etc.

Thanks.

**Comment by carr123** [comment] 2021-08-11 02:58
@derekcollison @wallyqs 
hello, i make 2 video files, that show how i perform the test.

https://github.com/carr123/natsjsmdemo/blob/main/out1.mp4
https://github.com/carr123/natsjsmdemo/blob/main/out2.mp4

BTW， there are 3 streams in my nats server, 2 for business usage,  1 for my test purpose.
i wonder whether the 3 streams influence each other.
or, i made too many tests these days, made too many config file changes , left the whole nats-server a mess.

**Comment by derekcollison** [comment] 2021-08-11 03:01
Thanks! @wallyqs and @variadico will take a look.

**Comment by carr123** [comment] 2021-08-11 10:02
@derekcollison  I just stop the cluster, delete all jetstream folders on all the 3 server nodes.  make a completely clean environment.
all the server config files keep the same as before.   then perform the jetstream test.
luckly, my client program this time can successfully fetch messages after server restart.
i modified the server config files and restart servers many times during the passed month.
maybe there are some dirty data in the jetstream folder that cause the fetching issue.
thanks for your attention. i will make more test.

**Comment by derekcollison** [comment] 2021-08-11 14:01
Let's keep this open til we really figure out what you are experiencing and make sure we understand what is going on.

**Comment by carr123** [comment] 2021-08-12 00:48
yes, you are right. the problem appear again.
12 hours ago, i made a clean nat-server deployment, did some restart test, everything was ok.
then i keep the reveiver program running, the sender program send 10000 messages every 3 hours, it's not heavy workload.
12 hours passed, i get to office, notice the same amount of messages was recevied as they were sent. nothing wrong.
then testing work started, this time i kill all the 3 nodes one by one, start them one by one,  nc.SetDisconnectErrHandler callback indeed received "EOF“，after that all nodes are alive again.  i send 5000 message, client program fail to fetch any one, printing fetch timeout.   i restart  client program, still fetch timeout.  
i uncomment the code "DeleteConsumer( ) ",  messags are fetched again.
after that, everything seems go back to normal.     i send more and more messages, all are received as long as nats-server no been restarted.

i find there are 3 kinds of errors after  nats-server restart:
1. client program can start and try to fetch messages, but always fetch timeout while there are many messages in the working queue.
2.  js.AddConsumer( ) return err:  "context deadline exceeded" each time i start the client program, i regard it as init faild and exit program.
3. sub.Fetch() always return err: "nats: no messages" in every fetch call

**Comment by derekcollison** [comment] 2021-08-12 01:59
ok I introduced a bug that is in the Go client (main branch) that will cause pull subscribers to fail after a reconnect of the client connection. So it could be that. We should have a fix in later tonight or tomorrow.

What is the git tag/version of the Go client you are using?

**Comment by carr123** [comment] 2021-08-12 03:32
@derekcollison i use the latest code.  i have network problem to use "go get github.com/nats-io/nats.go" command.
so i download it manually from  "https://github.com/nats-io/nats.go/archive/refs/heads/master.zip"  about 7 days ago.
if you find the cause, that's a good news.

**Comment by carr123** [comment] 2021-08-18 01:08
@derekcollison hi, i wonder if you already have any clue about this issue.
i recently perform a test on windows 10, different environment from the former linux server.
problem still found.  i know little about nats source codes, i hava no idea whether my config files have problem or the server side have problem.
this's my client problems and server configs.

https://github.com/carr123/jsmwindows

**Comment by derekcollison** [comment] 2021-08-20 14:28
In the example above, how are you stopping the servers?
What do you mean by changing the account password? Do you reload the server config?

**Comment by carr123** [comment] 2021-08-24 00:13
on windows 10, servers are running in CMD window, stopping it just issue a CTRL+C 
changing the account password means i want to pick up a better password for some account , then restart all servers.
all operations are normal.
just restarting the servers one time may not reproduce the issue.  i test it manually for many times, the issue will finally show up.
i mean if you want to see it , repeated manual testing will lead you to it.

**Comment by ripienaar** [comment] 2021-08-24 14:26
@carr123  your test programs have ```nats.MaxReconnects(10),``` are you 100% sure you dont hit 10 reconnect and then it stalls? I'd make that `-1` while testing

**Comment by carr123** [comment] 2021-08-25 06:45
> @carr123 your test programs have `nats.MaxReconnects(10),` are you 100% sure you dont hit 10 reconnect and then it stalls? I'd make that `-1` while testing

@ripienaar @wallyqs @derekcollison  hi, i tried, nats.MaxReconnects(-1) still doesn't work.
i find a way to reproduce this issue easier on windows 10 when i perform the restart test.
i start 3 cmd.exe windows running nats cluster nodes locally.
it i close the cmd.exe window by clicking the close button on the top-right, not by issuing an CTRL+C command,
then the problem show up more often.

**Comment by carr123** [comment] 2021-08-30 12:12
@derekcollison  hello, i buy a windows server from a cloud service provider.  testing programs are deployed.
and an email has sent to derek@nats.io, you can check it.
thanks.

**Comment by ColinSullivan1** [comment] 2021-08-30 22:58
@carr123 Thank you so much for your patience with this issue and going to the lengths you have to help us debug this - much appreciated.  We were able to reproduce this and already have some ideas about what could be causing the issue.  We'll keep you posted.

**Comment by carr123** [comment] 2021-08-31 00:40
@ColinSullivan1   hi, you can download it from  http://101.200.84.208/natstest.zip
this download URL will expire in 6 days. 
if you can't download it,  let me know, then i will send the file to you by email attachment when i could.

**Comment by derekcollison** [comment] 2021-08-31 18:22
Thanks, link does not seem to work though.. Just hangs. I can see the server is up and pingable but clicking on link or even curl fails.

**Comment by carr123** [comment] 2021-08-31 22:30
hi, Wally download it, so i close the download link.   now, i reopen it, should be accessible.http://101.200.84.208/natstest.zip

**Comment by derekcollison** [comment] 2021-08-31 22:35
We got it and can reproduce it from time to time. Thanks for your patience, I am looking at it now.

**Comment by wallyqs** [comment] 2021-09-01 18:55
Hi @carr123 one quick note is that I noticed that you were using `QUIT` to stop the server. To restart the server gracefully `TERM`, `INT` and `USR2` would help avoid reaching this state as well: https://github.com/nats-io/nats.docs/blob/030567b573ee75c71bfe3f810c49425391599637/nats-server/nats_admin/signals.md#signals
Thanks again for all the info helping reproduce this issue.

**Comment by wallyqs** [comment] 2021-09-01 22:16
> if i close the cmd.exe window by clicking the close button on the top-right,

@carr123 we were not handling this event properly and so this would have become a bad exit that hit another bug from the server when restarting. The behavior when stopping the server this way has been improved in the `main` branch :)

**Comment by carr123** [comment] 2021-09-01 22:34
a resilient system should consider bad exit like process kill，unexpected power off，a node could exit at any time。
it's hard to design distributed systems. 
thanks for your work！

发自我的iPhone

**Comment by derekcollison** [comment] 2021-09-02 00:08
We agree 100% in terms of bad exits etc. But Wally found out the normal behavior on Windows was not correct.

**Comment by derekcollison** [comment] 2021-09-02 00:09
Feel free to try this out. Docker synadia/nats-server:nightly

**Comment by derekcollison** [comment] 2021-09-02 00:09
Should be fixed, and thanks again for your patience.

**Closed by derekcollison** 2021-09-02 00:09 UTC
Labels: 🐞 bug

**Comment by kozlovic** [comment] 2021-09-02 00:11
Although the Go client issue reported here: https://github.com/nats-io/nats.go/issues/809, may then add to the issue that @carr123 is now experiencing with v2.4.0 and client v1.12.0. I am working on a client fix at the moment.

**Comment by carr123** [comment] 2021-09-02 06:24
hi, i just download nats-server main branch, build binary,  do the node restart test.  
Go client v1.12.0
nats-server platform: windows and linux, amd64
everything runs well.  the cluster can survive random node restart.
thanks for your work !
