### ISSUE TITLE
NATS Routing - With Super Clusters

### ISSUE THREAD

**Issue by Hitesh-Agrawal** [nats-io/nats-server#1329] opened 2020-04-08 12:17 UTC
- [ ] Feature Request or Change Proposal
Currently we have 3 NATS Cluster in each region.
US - Cluster 1
Europe - Cluster 2
Asia - Cluster 3 . 
We see a full service mesh created between our nats nodes with 1 gateway server in each cluster , which has knowledge about the gateway server in remote cluster.
Hence any topic published from US node directly reaches to a NATS subscriber in Asia.
Now the RTT from US to Asia is 8 ms , but if we go from US ->. Europe ->. Asia ( we have a better path of only 5ms). Can this be done. AM I missing something.

![image](https://user-images.githubusercontent.com/39374310/78783239-e9b73080-79c0-11ea-9e23-cea44c219bc0.png)

 

 - [ ] Included `[64] 2020/04/08 12:12:13.128499 [INF] Starting nats-server version 2.1.6
[64] 2020/04/08 12:12:13.128527 [DBG] Go build version go1.13.9
[64] 2020/04/08 12:12:13.128537 [INF] Git commit [8c8d6f8]` output
 - [ ] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)

**Comment by derekcollison** [comment] 2020-04-08 16:02
Gateways should be configured on all servers for a cluster, and are not designed to be a SPOF.

**Comment by derekcollison** [comment] 2020-04-08 16:04
You can look at the path that is taken to connect US and ASIA and use DNS and possibly VPNs to direct that traffic on a similar path as you have above through Europe.

You could also change topologies and have US and ASIA be leafnodes off of Europe.

**Comment by kozlovic** [comment] 2020-04-08 16:05
@Hitesh-Agrawal Each node in each cluster should have an outbound GW connection to 1 node in the other cluster. That is by design. So if a publisher connects to server 2 in cluster1, and that message has a subscription interest in cluster 3, server 2 will have a direct connection to one server in cluster3 and send that message. In cluster3, distribution of this message to a local or cluster consumer follows normal rules.
Messages cannot be sent from more than 1 hop cluster wise, that is, it would not be possible to send from cluster1->cluster2->cluster3.

**Comment by m4ce** [comment] 2020-04-08 16:34
@kozlovic / @derekcollison - isn't this a bit of a limitation though?

Say that we could connect US and ASIA directly over a vpn tunnel as you suggested. If there are subscribers interested in the same data in both EU and ASIA, data will effectively be travelling twice on the same pipe?

We are also trying to optimise how data travels around our network..

**Comment by kozlovic** [comment] 2020-04-08 16:38
> Say that we could connect US and ASIA directly over a vpn tunnel as you suggested. If there are subscribers interested in the same data in both EU and ASIA, data will effectively be travelling twice on the same pipe?

If message originates from US and there is interest in EU and ASIA, it will be sent to 2 different clusters: US->EU and US->ASIA yes.

**Comment by m4ce** [comment] 2020-04-08 16:48
@kozlovic, thanks for confirming that, that's what we were afraid of. It's a shame that we cannot achieve this with NATS now - for some reasons, we were in the assumption that we could get this done with the new super-cluster technology. Do you see any plans for NATS to implement this sort of custom topologies in the future?

**Comment by kozlovic** [comment] 2020-04-08 16:54
@derekcollison Mentioned that instead of using gateways you would use LeafNodes that could work, however, not sure that it would if you still have 3 nodes per cluster.

As for gateways, I am not sure this would change. It would require:
- a server on any cluster to know about RTT for all "gateways" between each cluster to decide which way to go
- a server receiving from another cluster to send to another, which means a protocol that indicates the list of clusters this message originate from to avoid the loop
- possibly have dropped messages because one of the gateway connection is down between 2 clusters while the direct send would have made it (say GW from EU to ASIA from a given node just disconnects, while US to ASIA is still intact).

**Comment by derekcollison** [comment] 2020-04-08 16:58
Feel free to try a leafnode setup where US and Asia solicit leafnode connections to EU. That sounds like what you want.

**Comment by derekcollison** [comment] 2020-04-08 16:58
Do you use multiple accounts?

**Comment by m4ce** [comment] 2020-04-08 17:04
@derekcollison, we don't actually use accounts. However, it appears as if we can only have one leafnode in a given region? Typically, in every region we have three AZs where we run a nats node as part of the local cluster. We also want to distribute messages locally. Would we be able to that with leafnodes?

**Comment by derekcollison** [comment] 2020-04-08 17:40
You can run a small cluster that acts as a leafnode. Each server will form its own leafnode connection to the EU cluster. So you can keep the 3x3x3 setup.

**Comment by derekcollison** [comment] 2020-04-08 17:41
If you don't use accounts that makes it very easy to setup the leafnode setup we described.

**Comment by m4ce** [comment] 2020-04-08 18:31
@derekcollison, thanks, understood. Will try it out and report back. Just so I understand. This really only works in the case of Europe being the hub between Asia and US right? What if we add a new region, call it SouthAmerica and I want that to route via US->Europe to reach Asia? I suppose this will not be possible right?

**Comment by matthiashanel** [comment] 2020-04-08 19:05
@m4ce ,it is possible. Any acyclic graph topology can be configured: https://docs.nats.io/nats-server/configuration/leafnodes

**Comment by m4ce** [comment] 2020-04-08 19:20
@matthiashanel - thanks for the confirmation. This is all very useful. I will try this out and report back!

**Comment by derekcollison** [comment] 2020-04-08 19:20
Leafnodes allow hub and spoke architectures to and from clusters or super
clusters. So you can design the system however you choose.

**Comment by derekcollison** [comment] 2020-04-08 19:22
If you add SA as a leafnode to the main Europe cluster the traffic from US to Asia will still flow through Europe as will traffic from US to SA as well.

**Comment by m4ce** [comment] 2020-04-08 19:23
thanks @derekcollison - appreciate all your prompt responses! Let us try this out. If you could just leave this issue open until we report back, hopefully tomorrow by EOD.

**Comment by m4ce** [comment] 2020-04-09 09:22
I am really impressed - I indeed tested with leafnodes and it works as you guys described. We are able to build any topology we want.

To confirm - if a cluster has a leafnode, all the nodes of that cluster need configuring as leafnodes right? Additionally, when setting up the remote urls, I guess I only need to specify one node of the remote cluster? If I specify more than one, it seems to detect a loop?

Topology:

A -> B <- C

so A to reach C needs to traverse B

See the configs below:

**A cluster:**

node A1:
```
listen: 0.0.0.0:4601

cluster {
  listen: localhost:5601

  routes = [
    nats-route://127.0.0.1:5602
    nats-route://127.0.0.1:5603
  ]
}

leafnodes {
    port: 7601
    remotes = [
        {
          url: "nats-leaf://localhost:7701"
        }
    ]
}
```

node A2:
```
listen: 0.0.0.0:4602

cluster {
  listen: localhost:5602

  routes = [
    nats-route://127.0.0.1:5601
    nats-route://127.0.0.1:5603
  ]
}

leafnodes {
    port: 7602
    remotes = [
        {
          url: "nats-leaf://localhost:7701"
        }
    ]
}
```

node A3:
```
listen: 0.0.0.0:4603

cluster {
  listen: localhost:5603

  routes = [
    nats-route://127.0.0.1:5601
    nats-route://127.0.0.1:5602
  ]
}

leafnodes {
    port: 7603
    remotes = [
        {
          url: "nats-leaf://localhost:7701"
        }
    ]
}
```

**B cluster:**

node B1:
```
listen: 0.0.0.0:4701

cluster {
  listen: localhost:5701

  routes = [
    nats-route://127.0.0.1:5702
    nats-route://127.0.0.1:5703
  ]
}

leafnodes {
    port: 7701
}
```

node B2:
```
listen: 0.0.0.0:4702

cluster {
  listen: localhost:5702

  routes = [
    nats-route://127.0.0.1:5701
    nats-route://127.0.0.1:5703
  ]
}

leafnodes {
    port: 7702
}
```

node B3:
```
listen: 0.0.0.0:4703

cluster {
  listen: localhost:5703

  routes = [
    nats-route://127.0.0.1:5701
    nats-route://127.0.0.1:5702
  ]
}

leafnodes {
    port: 7703
}
```

**C cluster:**

node C1:
```
listen: 0.0.0.0:4801

cluster {
  listen: localhost:5801

  routes = [
    nats-route://127.0.0.1:5802
    nats-route://127.0.0.1:5803
  ]
}

leafnodes {
    port: 7801
    remotes = [
        {
          url: "nats-leaf://localhost:7701"
        }
    ]
}
```

node C2:
```
listen: 0.0.0.0:4802

cluster {
  listen: localhost:5802

  routes = [
    nats-route://127.0.0.1:5801
    nats-route://127.0.0.1:5803
  ]
}

leafnodes {
    port: 7802
    remotes = [
        {
          url: "nats-leaf://localhost:7701"
        }
    ]
}
```

node C3:
```
listen: 0.0.0.0:4803

cluster {
  listen: localhost:5803

  routes = [
    nats-route://127.0.0.1:5801
    nats-route://127.0.0.1:5802
  ]
}

leafnodes {
    port: 7803
    remotes = [
        {
          url: "nats-leaf://localhost:7701"
        }
    ]
}
```

The configs do work but would like to have the thumbs-up from you guys to make sure we are not missing anything important.

**Comment by m4ce** [comment] 2020-04-09 13:38
I guess `urls` needs to be used when specifying multiple leafnodes (belonging to the same cluster)? if I split them in separate blocks ({url: ..}, I see loops..

**Comment by matthiashanel** [comment] 2020-04-09 15:38
@m4ce In your example you probably want to use `urls` pointing to each server of the cluster B. Below is your example for A1 re-written with urls pointing to each server in cluster B. In each configured remote A1 will connect to one server in the urls list. By configuring multiple `urls`, you can connect into B even if B1 is down.

If you have control over your DNS records and Servers B1/B2/B3 can be reached via the same DNS name, having a single url using that name is sufficient, recommended even. 

Also, since you don't have anyone connect into A, you won't need a leafnode port.
```
listen: 0.0.0.0:4601

cluster {
  listen: localhost:5601

  routes = [
    nats-route://127.0.0.1:5602
    nats-route://127.0.0.1:5603
  ]
}

leafnodes {
    remotes = [
        {
          urls: ["nats-leaf://localhost:7701", "nats-leaf://localhost:7702", "nats-leaf://localhost:7703"]
        }
    ]
}
```

Each remote corresponds to a connection to another cluster/system. In the context of your example, having two remotes would mean you specified a topology with a loop.

**Comment by m4ce** [comment] 2020-04-09 15:47
@matthiashanel, thanks for the updated example.

Just so I understand further. We could mix gateways and leafnodes too right?

Suppose we have another region D, I could create a mesh between C and D using the gateways and have both cluster being leaf nodes of B right?

**Comment by m4ce** [comment] 2020-04-09 16:14
Ah, again, looks like I should only set the leafnodes only on one of the clusters that are part of the same mesh, else I get a loop again?

**Comment by matthiashanel** [comment] 2020-04-09 16:32
You beat me to it. As this is stretching my experience a bit, was about to try it myself...

Interest flows bidirectionally between C and D, and C and B and D and B. This would make a circle. Hence only one of the clusters should connect to B.

For your concrete example where you used leaf nodes already, I would not have used gateways to connect C and D. I'd start considering them once you have a third cluster in the mix. Then auto discovery can keep config smaller and the full mesh would remove one hop somewhere. 

- You can have all cluster in the gateway connect to a single cluster, form that cluster each cluster will learn about others.
- Say you have hub and spoke configured using leaf nodes (C-D-E), a gateway would directly connect C and E as well.

**Comment by m4ce** [comment] 2020-04-09 16:47
Thanks @matthiashanel - all clear. I think I have all that I need to make progress. I hope this issue will help other people figure out how to use gateways and leafnodes in different topologies. If I have any other question, I will reach out on Slack.

Many thanks again everyone for the help!

**Comment by derekcollison** [comment] 2020-06-02 02:28
Closing for now, feel free to re-open if needed.

**Closed by derekcollison** 2020-06-02 02:28 UTC
