### ISSUE TITLE
Duplicates message received while consuming with leafnode connection

### ISSUE THREAD

**Issue by asambres-form3** [nats-io/nats-server#3191] opened 2022-06-14 15:18 UTC
## Defect

Messages are delivered twice to the same client.

The NATS client receives each message 2 times.
Both messages are delivered almost at the same time (<10ms delta) and are identical (Same headers, sequence id, body, delivery count)

- We experience this issue on all our environments
- We are able to reproduce the issue in a local kind cluster
- Unfortunately we are not able to make up a deterministic procedure to create the issue
- We need to restart servers multiple times in a sequence we could not understand for the problem to appear

#### Versions of `nats-server` and affected client libraries used:
[nats-server v2.8.4](https://github.com/nats-io/nats-server/releases/tag/v2.8.4)  
[nats.go v1.16.0](https://pkg.go.dev/github.com/nats-io/nats.go@v1.16.0)

#### OS/Container environment:
Running nats in Kubernetes cluster with official [helm chart](https://docs.nats.io/running-a-nats-service/nats-kubernetes/helm-charts).

#### Steps or code to reproduce the issue:

Setup diagram:
![jetstream-issue](https://user-images.githubusercontent.com/95638921/173613290-fdbeb160-fba0-42e8-ad08-71061539e41e.png)

Given:
 - 2 nats clusters (A and B) composed of 2 nats-server instances each with jetstream running on all instances
 - Cluster A establishes leaf node connections to the cluster B
 - A go service (Application 1, Application 2) using the client lib version `nats.go@1.16.0` is connected to the cluster B and consumes messages from a stream that lives in the cluster A (thus via a leafnode connection).
 
When:
 - an unexpected sequence of events happen, nats server restarts, network partitions...
 
Then:
 - the cluster enters incoherent state and doesn't recover (all nodes running, no network partition)
 - The application instance receives each messages 2 times 
 - The duplicated messages are received in the same millisecond on the same instance
 - Restarting the application does not resolve the issue
 - The issue does not self resolve with time
 - Messages are systematically and constantly received 2 times.
 - Restarting the nats-server that sends the duplicates (the one which the client is connected to) is the ONLY way to stop that problem

Logs from a NATS server that sends duplicates (duplicates start at sequence 104):
[nats-0-trace.log](https://github.com/nats-io/nats-server/files/8901072/nats-0-trace.log)

#### Expected result:

Each message should be received once from the same consumer or subscription.

#### Actual result:

The go client subscribing to the remote consumer receives duplicated message.

**Comment by derekcollison** [comment] 2022-06-14 17:18
This situation seems to have quite a few moving pieces, some we know and some are probably not known to us. Recreating this and trying to reproduce could take several hours and we might not see anything in our setup. So, I would suggest we jump on a Zoom call and triage. Are you able to reproduce predictably?

**Comment by mlornac** [comment] 2022-06-15 07:33
@derekcollison Yes we can reproduce semi predictably. 
If that works for you we can prepare the cluster to be in that situation before we jump on a call. 
When would you have some availability?

**Comment by derekcollison** [comment] 2022-06-15 14:04
If extremely important on your side I could do early PT tomorrow, otherwise early PT Monday as I am traveling to customers starting mid-day tomorrow.

Shoot me an email, derek@synadia.com

**Comment by derekcollison** [comment] 2022-06-30 18:26
Sounds like ensuring the cluster names are unique might have resolved?
ok to close?

We are looking at ways the system can help out when we detect this situation.

**Comment by bloodbare** [comment] 2022-08-12 21:48
We have the same problem with a leafnode and a source copy on the same account, for each message, two appears on the origin stream and the destination stream. Mirror on the other direction works properly.

**Comment by kozlovic** [comment] 2022-09-02 14:58
@bloodbare Would you be able to send the configuration file of all server involved and the configuration of the JS consumer you use (if any). I see the subscription output, but not sure how you started the sub (where it connects to, what command line params you use, etc..). In short anything that you could provide to me so I can reproduce the setup and see the issue. Thanks!

**Comment by TomasVojacek** [comment] 2022-09-02 17:13
I saw something similar. Our setup is
mqtt-> jetstream on leafnode->sourcing jetstream
and When I do plain nats subsribe to "msg.originating.in.mqtt" I got duplicate messages.
I did not checked jetstreams messages detaily so I'm not sure if they exist there too.

**Comment by chenchunping** [comment] 2022-10-31 11:44
I also found the same problem in use, and the configuration is basically similar to yours.

**Comment by chenchunping** [comment] 2022-10-31 11:47
> 我在使用中也发现了同样的问题，配置和你的基本差不多。

<img width="531" alt="image" src="https://user-images.githubusercontent.com/29721558/199000836-7a25e338-4b5d-4ee1-be52-94e2db2c26af.png">

**Comment by chenchunping** [comment] 2022-10-31 11:49
I also found the same problem in use, and the configuration is basically similar to yours.
<img width="525" alt="image" src="https://user-images.githubusercontent.com/29721558/199000912-e4d05921-76d5-457c-a0d5-dd62b72740f2.png">
When I am linking cluster A pub message, cluster B sub message, if not linked to the leader of cluster B, then there will be duplicate messages

**Comment by derekcollison** [comment] 2022-10-31 21:26
What is the stated cluster name for A_1 and A_2? and likewise B_1 and B-2?

Also if involving JetStream they need to have unique and distinct domains.

Possible to share the configs for all servers as @kozlovic mentioned?

**Comment by chenchunping** [comment] 2022-11-01 02:59
> What is the stated cluster name for A_1 and A_2? and likewise B_1 and B-2?
> 
> Also if involving JetStream they need to have unique and distinct domains.
> 
> Possible to share the configs for all servers as @kozlovic mentioned?

When sub directly links the cluster, there is a certain chance of receiving duplicate data (if the link of this client is load balanced to the normal one node will send and receive normally, otherwise it will be duplicated) and so will jetstream
In the case I create the link inside the loop and pub/sub, and close the link at the end of each loop, the test code is like this.
for i := 0; i < 50; i++ {
	subject := "iot.b.topic"
	producer := &natsServer{
		user:          "usera",
		pass:          "usera",
		natsServerurl: "nats://127.0.0.1:14223",
	}
	consumer := &natsServer{
		user:          "userb",
		pass:          "userb",
		natsServerurl: "nats://127.0.0.1:24222,nats://127.0.0.1:24223",
	}
	// pub ends the message and exits the sub listener
	pubEndSingle := make(chan bool, 1)
        // sub fully exit, you can exit the main program
	subEndSingle := make(chan bool, 1)
        // sub listener starts and notifies pub that it is ready to run
	subStarSingle := make(chan bool, 1)
	var messageCount = 10
	go natsSub(subject, *consumer, messageCount, pubEndSingle, subEndSingle, subStarSingle)
	<-subStarSingle
	natsPub(subject, *producer, messageCount)
	pubEndSingle <- true
	<-subEndSingle
}

Result：
2022/11/01 10:27:34 Published [iot.b.topic] : 'hello ->2022-11-01 10:27:34.704'
client:15 receive message hello ->2022-11-01 10:27:34.704
client:15 receive message hello ->2022-11-01 10:27:34.704
2022/11/01 10:27:36 Published [iot.b.topic] : 'hello ->2022-11-01 10:27:36.805'
client:15 receive message hello ->2022-11-01 10:27:36.805
client:15 receive message hello ->2022-11-01 10:27:36.805
>>>>>>>>>>>>>  close conn，clientId 15,err:<nil>: pub 10 recv 20, repect:true

2022/11/01 10:27:38 client id :18 Listening on [iot.b.topic]
2022/11/01 10:27:38 Published [iot.b.topic] : 'hello ->2022-11-01 10:27:38.989'
client:18 receive message hello ->2022-11-01 10:27:38.989
2022/11/01 10:27:41 Published [iot.b.topic] : 'hello ->2022-11-01 10:27:41.090'
client:18 receive message hello ->2022-11-01 10:27:41.090
2022/11/01 10:27:43 Published [iot.b.topic] : 'hello ->2022-11-01 10:27:43.192'
client:18 receive message hello ->2022-11-01 10:27:43.192


Here is my configuration：
￼

**A_1.conf**
http_port : 18222
cluster : {
  name : A
  port : 15333
  routes : [nats-router://127.0.0.1:15333,nats-router://127.0.0.1:15334]
}
leafnodes : {
  port : 14333
  remotes : [{
    account : A
    urls : [nats-leaf://_AConnUser_:_AConnUser_@127.0.0.1:24333,nats-leaf://_AConnUser_:_AConnUser_@127.0.0.1:24334]
  }]
}
jetstream {
  store_dir: "/Users/ccp/Documents/git/data/storage/jetstream/A_1"
  domain: A
}
port : 14222
server_name : A_1

accounts:{
  A:{
    jetstream: enabled
    users:[
      {user: _AConnUser_, password: _AConnUser_},
      {user: usera, password: usera, permissions: {
        publish:{
          allow:["iot.b.topic"]
        },
        subscribe:{
          allow:["iot.a.topic"]
        }
      }}
    ]
    imports:[
      {stream:{account:"B", subject:"iot.a.topic"}}
    ]
  },
  B:{
    jetstream: enabled
    users:[
      {user: _BConnUser_, password: _BConnUser_},
    ]
    exports:[
      {stream: "iot.a.topic", accounts: ["A"]}
    ]
  }
}

=========================================================

**A_2.conf**
http_port : 18223
cluster : {
  name : A
  port : 15334
  routes : [nats-router://127.0.0.1:15333,nats-router://127.0.0.1:15334]
}
leafnodes : {
  port : 14334
  remotes : [{
    account : A
    urls : [nats-leaf://_AConnUser_:_AConnUser_@127.0.0.1:24333,nats-leaf://_AConnUser_:_AConnUser_@127.0.0.1:24334]
  }]
}
jetstream {
  store_dir: "/Users/ccp/Documents/git/data/storage/jetstream/A_2"
  domain: A
}
port : 14223
server_name : A_2

accounts:{
  A:{
    jetstream: enabled
    users:[
      {user: _AConnUser_, password: _AConnUser_},
      {user: usera, password: usera, permissions: {
        publish:{
          allow:["iot.b.topic"]
        },
        subscribe:{
          allow:["iot.a.topic"]
        }
      }}
    ]
    imports:[
      {stream:{account:"B", subject:"iot.a.topic"}}
    ]
  },
  B:{
    jetstream: enabled
    users:[
      {user: _BConnUser_, password: _BConnUser_},
    ]
    exports:[
      {stream: "iot.a.topic", accounts: ["A"]}
    ]
  }
}


=========================================================

**B_1.conf**
http_port : 28222
cluster : {
  name : B
  port : 25333
  routes : [nats-router://127.0.0.1:25333,nats-router://127.0.0.1:25334]
}
leafnodes : {
  port : 24333
  remotes : [{
    account : B
    urls : [nats-leaf://_BConnUser_:_BConnUser_@127.0.0.1:14333,nats-leaf://_BConnUser_:_BConnUser_@127.0.0.1:14334]
  }]
}
jetstream {
  store_dir: "/Users/ccp/Documents/git/data/storage/jetstream/B_1"
  domain: B
}
port : 24222
server_name : B_1

accounts:{
  A:{
    jetstream: enabled
    users:[
      {user: _AConnUser_, password: _AConnUser_},
    ]
    exports:[
      {stream: "iot.b.topic", accounts: ["B"]}
    ]
  },
  B:{
    jetstream: enabled
    users:[
      {user: _BConnUser_, password: _BConnUser_},
      {user: userb, password: userb, permissions: {
        publish:{
          allow:["iot.a.topic"]
        },
        subscribe:{
          allow:["iot.b.topic"]
        }
      }}
    ]
    imports:[
      {stream:{account:"A", subject:"iot.b.topic"}}
    ]
  }
}

=========================================================


**B_2.conf**
http_port : 28223
cluster : {
  name : B
  port : 25334
  routes : [nats-router://127.0.0.1:25333,nats-router://127.0.0.1:25334]
}
leafnodes : {
  port : 24334
  remotes : [{
    account : B
    urls : [nats-leaf://_BConnUser_:_BConnUser_@127.0.0.1:14333,nats-leaf://_BConnUser_:_BConnUser_@127.0.0.1:14334]
  }]
}
jetstream {
  store_dir: "/Users/ccp/Documents/git/data/storage/jetstream/B_2"
  domain: B
}
port : 24223
server_name : B_2

accounts:{
  A:{
    jetstream: enabled
    users:[
      {user: _AConnUser_, password: _AConnUser_},
    ]
    exports:[
      {stream: "iot.b.topic", accounts: ["B"]}
    ]
  },
  B:{
    jetstream: enabled
    users:[
      {user: _BConnUser_, password: _BConnUser_},
      {user: userb, password: userb, permissions: {
        publish:{
          allow:["iot.a.topic"]
        },
        subscribe:{
          allow:["iot.b.topic"]
        }
      }}
    ]
    imports:[
      {stream:{account:"A", subject:"iot.b.topic"}}
    ]
  }
}


**Thank you sincerely for your help!**

**Comment by chenchunping** [comment] 2022-11-02 02:55
> What is the stated cluster name for A_1 and A_2? and likewise B_1 and B-2?
> 
> Also if involving JetStream they need to have unique and distinct domains.
> 
> Possible to share the configs for all servers as @kozlovic mentioned?

Is it not possible to create a bi-directional leafconn using an unavailable account?
but I tested and found that the bi-directional linking of leafconn is allowed when I start the standalone

**Comment by kozlovic** [comment] 2022-11-02 14:48
@chenchunping Thank you for providing the configuration files and step to reproduce. I am going to set that up and see if I can reproduce and make sense of what is going on. It is for sure a pretty complex setup (leafs to each other and accounts imports/exports). I will update this ticket as soon as I can.

**Comment by kozlovic** [comment] 2022-11-03 00:24
@chenchunping Just an update that I have made some progress and will resume work tomorrow.

**Comment by kozlovic** [comment] 2022-11-03 19:00
Note that PR #3604 addresses the issue reported by @chenchunping (with the provided configuration files and steps to reproduce). If the original poster and others that posted before that still experience the duplicate issue after upgrading to v2.9.6 (to be released with a fix for the duplicate messages), please try to provide all configuration files and steps to reproduce similar to @chenchunping. Thanks!

**Comment by chenchunping** [comment] 2022-11-04 00:33
> Note that PR #3604 addresses the issue reported by @chenchunping (with the provided configuration files and steps to reproduce). If the original poster and others that posted before that still experience the duplicate issue after upgrading to v2.9.6 (to be released with a fix for the duplicate messages), please try to provide all configuration files and steps to reproduce similar to @chenchunping. Thanks!

I've tested this issue after upgrading nats 2.9.6 and it doesn't occur anymore, thank you very much for fixing this issue so quickly.
We rely heavily on nats in our business and I'd like to know why this is causing duplicate messages, can you email（929626251@qq.com） or github me if you can?

**Comment by chenchunping** [comment] 2022-11-04 00:35
> Note that PR #3604 addresses the issue reported by @chenchunping (with the provided configuration files and steps to reproduce). If the original poster and others that posted before that still experience the duplicate issue after upgrading to v2.9.6 (to be released with a fix for the duplicate messages), please try to provide all configuration files and steps to reproduce similar to @chenchunping. Thanks!

Thank you both @kozlovic @derekcollison

**Comment by kozlovic** [comment] 2022-11-04 16:54
@chenchunping As I have described in the PR it had to do with the fact that accounts import/export rules cause server to create a "shadow" subscription on the import subject on behalf of the account. This subscription was incorrectly propagated across the leafnodes which cause the message to go back and forth due to the subject being the same, which caused a duplicate.
We are glad that the issue is now resolved.

**Comment by maxarndt** [comment] 2022-11-11 08:13
@kozlovic @derekcollison when I saw the recent changelog of v2.9.6 I was looking forward to seeing if #2694 has been resolved as well. In fact, behavior has changed but unfortunately it has not been fixed completely. I updated https://github.com/nats-io/nats-server/issues/2694#issuecomment-1311366988.

By the way, great event and great presentations yesterday at RethinkConn!

**Comment by derekcollison** [comment] 2022-11-11 16:55
Thanks, will take a look.

**Comment by derekcollison** [comment] 2022-12-07 02:31
@maxarndt if their are imports and exports on both clusters separated by a leaf node that are applicable to the same message you will get duplicates. 

The hub side of the system does not understand anything about what is on the leafnode cluster, by design since it separates operational and security domains.

**Comment by derekcollison** [comment] 2022-12-07 02:34
@asambres-form3 after the network break, does nats-server-1 from cluster A re-establish a solicited leafnode connection or does it stay disconnected?

Also where is the publishing application connected? Cluster-A or Cluster-B?

**Comment by derekcollison** [comment] 2022-12-07 15:48
@asambres-form3 I now have a complete test that shows the issue. Will circle back when I know more.

**Comment by derekcollison** [comment] 2022-12-07 16:18
Actually I was incorrect, the test passes ok, was a typo in the test.

Will keep digging.

**Comment by derekcollison** [comment] 2022-12-07 20:48
https://github.com/nats-io/nats-server/pull/3694

**Closed** 2022-12-29 23:39 UTC
Labels: 🐞 bug
