### ISSUE TITLE
Ability to update durable consumer parameters after creation

### ISSUE THREAD

**Issue by rjoly-qlik** [nats-io/nats-server#2661] opened 2021-11-01 19:18 UTC
## Feature Request
I’m experimenting with the JetStream capabilities using the latest NATS server & NATS.JS client library.  I created a durable client and things generally behave as I expect however I’m looking for a way to tweak the consumer’s parameters after creation but they seem to stick to whatever I set them to when I originally created it.

#### Use Case:
I deploy a new micro-service and I conservatively set the `maxAckPending()` value to `5`.  After observation and a few optimizations, it is determined that it could actually handle `10` parallel requests instead of `5` so the micro-service’s code that sets the `consumerOpts` is updated to set the `maxAckPending()` value to `10` instead of `5` and the micro-service is redeployed, however, after the re-deployment I see via the NATS CLI that the `Max Ack Pending` has remained at `5`. 

#### Proposed Change:
Similar to what `NATS-Streaming` can do, it should be possible to change the configuration of a durable client after it has been created. 

#### Who Benefits From The Change(s)?
Every JetStream user that may consider making tweaks to their durable consumer past day 1. 

#### Alternative Approaches
no real alternatives as per this [Slack conversation](https://natsio.slack.com/archives/CM3T6T7JQ/p1635792560187400?thread_ts=1635790851.184700&cid=CM3T6T7JQ).

**Comment by andreib1** [comment] 2021-11-01 19:21
This looks like a duplicate of https://github.com/nats-io/nats-server/issues/2603

**Comment by rjoly-qlik** [comment] 2021-11-01 19:23
> This looks like a duplicate of #2603

@andreib1 It sure does.  I missed it when browsing through the history of issues.  Thanks for digging this out.

**Comment by andreib1** [comment] 2021-11-01 19:24
No worries @rjoly-qlik :)

**Comment by derekcollison** [comment] 2021-11-02 21:42
Closing in favor of #2603, will track there. Thanks. I think we can do something.

**Closed by derekcollison** 2021-11-02 21:42 UTC
Labels: 🎉 enhancement
